package tapgarden

import (
	"context"
	"errors"
	"fmt"

	"github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/chaincfg/chainhash"
	"github.com/btcsuite/btcd/wire"
	"github.com/lightninglabs/taproot-assets/asset"
	"github.com/lightninglabs/taproot-assets/commitment"
	"github.com/lightninglabs/taproot-assets/fn"
	"github.com/lightninglabs/taproot-assets/proof"
	"github.com/lightninglabs/taproot-assets/tapsend"
	"github.com/lightningnetwork/lnd/keychain"
)

const (
	// IssuanceTxLabel defines the label assigned to an on-chain transaction
	// that represents a tapd asset issuance.
	IssuanceTxLabel = "tapd-asset-issuance"
)

// BatchState an enum that represents the various stages of a minting batch.
type BatchState uint8

const (
	// BatchStatePending denotes that the batch is pending and may have
	// some assets allocated to it.
	BatchStatePending BatchState = 0

	// BatchStateFrozen denotes that a batch is frozen, and no new
	// seedlings can be added to it.
	BatchStateFrozen BatchState = 1

	// BatchStateCommitted denotes that a batch now has an unsigned genesis
	// PSBT packet and the set of seedlings have been made into sprouts
	// with all relevant fields populated.
	BatchStateCommitted BatchState = 2

	// BatchStateBroadcast denotes a batch now has a fully signed genesis
	// transaction and can be broadcast to the network.
	BatchStateBroadcast BatchState = 3

	// BatchStateConfirmed denotes that a batch has confirmed on chain, and
	// only needs a sufficient amount of confirmations before it can be
	// finalized.
	BatchStateConfirmed BatchState = 4

	// BatchStateFinalized is the final state for a batch. In this terminal
	// state the batch has been confirmed on chain, with all assets
	// created.
	BatchStateFinalized BatchState = 5

	// BatchStateSeedlingCancelled denotes that a batch has been cancelled,
	// and will not be passed to a caretaker.
	BatchStateSeedlingCancelled BatchState = 6

	// BatchStateSproutCancelled denotes that a batch has been cancelled
	// after being passed to a caretaker and sprouting.
	BatchStateSproutCancelled BatchState = 7
)

// String returns a human-readable string for the target batch state.
func (b BatchState) String() string {
	switch b {
	case BatchStatePending:
		return "BatchStatePending"

	case BatchStateFrozen:
		return "BatchStateFrozen"

	case BatchStateCommitted:
		return "BatchStateCommitted"

	case BatchStateBroadcast:
		return "BatchStateBroadcast"

	case BatchStateConfirmed:
		return "BatchStateConfirmed"

	case BatchStateFinalized:
		return "BatchStateFinalized"

	case BatchStateSeedlingCancelled:
		return "BatchStateSeedlingCancelled"

	case BatchStateSproutCancelled:
		return "BatchStateSproutCancelled"

	default:
		return fmt.Sprintf("UnknownState(%d)", b)
	}
}

// NewBatchState creates a BatchState from a uint8, returning an error if the
// input value does not map to a valid BatchState.
func NewBatchState(state uint8) (BatchState, error) {
	switch BatchState(state) {
	case BatchStatePending:
		return BatchStatePending, nil

	case BatchStateFrozen:
		return BatchStateFrozen, nil

	case BatchStateCommitted:
		return BatchStateCommitted, nil

	case BatchStateBroadcast:
		return BatchStateBroadcast, nil

	case BatchStateConfirmed:
		return BatchStateConfirmed, nil

	case BatchStateFinalized:
		return BatchStateFinalized, nil

	case BatchStateSeedlingCancelled:
		return BatchStateSeedlingCancelled, nil

	case BatchStateSproutCancelled:
		return BatchStateSproutCancelled, nil

	default:
		return BatchStateSproutCancelled,
			fmt.Errorf("unknown batch state: %v", state)
	}
}

// PreCommitBindData is the typed persistence payload that the
// BatchStore writes for a batch's pre-commitment output when the
// genesis-tx augmenter is active. The augmenter constructs it at
// funding and sealing time; tapgarden plumbs it opaquely through to
// the store. The store treats it as the source of truth for the
// columns of the supply-pre-commit table -- callers must not encode
// the same data through any other route.
type PreCommitBindData struct {
	// OutputIndex is the index of the pre-commitment output within
	// the batch mint anchor transaction.
	OutputIndex uint32

	// InternalKey is the Taproot internal public key associated
	// with the pre-commitment output.
	InternalKey keychain.KeyDescriptor

	// GroupKey is the asset-group public key for this
	// pre-commitment. Present when known (group reused at funding
	// time, or generated by seal time); absent while an unsealed
	// batch without a prior group key is still in progress.
	GroupKey fn.Option[btcec.PublicKey]
}

// BatchStore persists the lifecycle of a minting batch: creation,
// state transitions, and the writes that accompany each transition
// (sprouts, signed genesis tx, confirmation). Both the planter and
// the caretaker use it; the substance stored is exactly "minting
// batches and their state."
type BatchStore interface {
	// CommitMintingBatch commits a new minting batch to disk,
	// identified by its batch key. If preCommit is set (the
	// batch was created already-funded with a pre-commitment
	// output), the supply-pre-commit row is persisted in the
	// same transaction.
	CommitMintingBatch(ctx context.Context, newBatch *MintingBatch,
		preCommit fn.Option[PreCommitBindData]) error

	// UpdateBatchState writes the new batch state to disk and, on
	// success, mirrors it into the in-memory batch. Either both writes
	// succeed and the in-memory state advances, or both stay at the
	// prior value. Callers must never mutate batch state by any other
	// route.
	UpdateBatchState(ctx context.Context, batch *MintingBatch,
		newState BatchState) error

	// AddSeedlingsToBatch adds a new seedling to an existing batch. Once
	// added this batch should remain in the BatchStatePending state.
	//
	// The "exactly one batch in BatchStatePending or BatchStateFrozen
	// at a time" invariant the planter relies on is enforced at the
	// DB layer by migration 000061 (a partial unique index on
	// asset_minting_batches). Callers may assume that any successful
	// CommitMintingBatch left the singleton slot occupied by exactly
	// the batch they just committed.
	AddSeedlingsToBatch(ctx context.Context, batchKey *btcec.PublicKey,
		seedlings ...*Seedling) error

	// FetchAllBatches fetches all the batches on disk.
	FetchAllBatches(ctx context.Context) ([]*MintingBatch, error)

	// FetchNonFinalBatches fetches all non-finalized batches, meaning
	// batches that haven't yet fully confirmed on chain.
	FetchNonFinalBatches(ctx context.Context) ([]*MintingBatch, error)

	// FetchMintingBatch is used to fetch a single minting batch specified
	// by the batch key.
	FetchMintingBatch(ctx context.Context,
		batchKey *btcec.PublicKey) (*MintingBatch, error)

	// SealBatch seals a batch by assigning and persisting asset
	// groups for the seedlings it contains. If preCommit is set,
	// the store also re-upserts the supply-pre-commit row with the
	// payload (the group key is typically only known by seal time).
	SealBatch(ctx context.Context, batch *MintingBatch,
		newAssetGroups []*asset.AssetGroup,
		preCommit fn.Option[PreCommitBindData]) error

	// FetchSeedlingGroups is used to fetch the asset groups for seedlings
	// associated with a funded batch.
	FetchSeedlingGroups(ctx context.Context, genesisOutpoint wire.OutPoint,
		anchorOutputIndex uint32,
		seedlings []*Seedling) ([]*asset.AssetGroup, error)

	// AddSproutsToBatch adds a new set of sprouts to the batch,
	// along with a GenesisPacket, that once signed and broadcast
	// with create the set of assets on chain. If preCommit is set,
	// the supply-pre-commit row is also persisted (or refreshed)
	// in the same transaction.
	//
	// NOTE: On success the batch transitions to BatchStateCommitted on
	// disk and the in-memory state of the supplied batch is advanced to
	// match. On failure neither moves.
	AddSproutsToBatch(ctx context.Context, batch *MintingBatch,
		genesisPacket *FundedMintAnchorPsbt,
		assets *commitment.TapCommitment,
		preCommit fn.Option[PreCommitBindData]) error

	// CommitSignedGenesisTx adds a fully signed genesis transaction to the
	// batch, along with the Taproot Asset script root, which is the
	// left/right sibling for the Taproot Asset tapscript commitment in the
	// transaction.
	//
	// NOTE: On success the batch transitions to BatchStateBroadcast on
	// disk and the in-memory state of the supplied batch is advanced to
	// match. On failure neither moves.
	CommitSignedGenesisTx(ctx context.Context, batch *MintingBatch,
		genesisTx *tapsend.FundedPsbt, anchorOutputIndex uint32,
		merkleRoot, tapTreeRoot, tapSibling []byte) error

	// MarkBatchConfirmed marks the batch as confirmed on chain. The passed
	// block location information determines where exactly in the chain the
	// batch was confirmed.
	//
	// NOTE: On success the batch transitions to BatchStateConfirmed on
	// disk and the in-memory state of the supplied batch is advanced to
	// match. On failure neither moves.
	MarkBatchConfirmed(ctx context.Context, batch *MintingBatch,
		blockHash *chainhash.Hash, blockHeight uint32,
		txIndex uint32, mintingProofs proof.AssetBlobs) error

	// CommitBatchFunding atomically persists the funded genesis
	// transaction, the optional tapscript sibling root hash, and
	// the optional supply-pre-commit row for a batch in a single
	// transaction. Either all writes succeed or none persists, so
	// a partial failure cannot leave the batch in an inconsistent
	// on-disk state.
	//
	// NOTE: The tapscript tree referenced by rootHash (if non-nil)
	// must already be committed to disk.
	CommitBatchFunding(ctx context.Context, batchKey *btcec.PublicKey,
		rootHash *chainhash.Hash,
		genesisTx FundedMintAnchorPsbt,
		preCommit fn.Option[PreCommitBindData]) error
}

// MintingRefReader exposes the read-only lookups the planter performs
// to validate seedlings before they enter a batch and to populate
// listings. These are not batch state; they are pre-existing reference
// data the planter consults but does not own.
type MintingRefReader interface {
	// FetchGroupByGroupKey fetches the asset group with a matching tweaked
	// key, including the genesis information used to create the group.
	FetchGroupByGroupKey(ctx context.Context,
		groupKey *btcec.PublicKey) (*asset.AssetGroup, error)

	// FetchScriptKeyByTweakedKey fetches the populated script key given the
	// tweaked script key.
	FetchScriptKeyByTweakedKey(ctx context.Context,
		tweakedKey *btcec.PublicKey) (*asset.TweakedScriptKey, error)

	// FetchAssetMeta fetches the meta reveal for an asset genesis.
	FetchAssetMeta(ctx context.Context, ID asset.ID) (*proof.MetaReveal,
		error)
}

var (
	// ErrNoGenesis is returned when fetching an asset genesis fails.
	ErrNoGenesis = errors.New("unable to fetch genesis asset")

	// ErrBatchAlreadySealed is returned when a minting batch is already
	// sealed.
	ErrBatchAlreadySealed = errors.New("batch is already sealed")
)
