// This file benchmarks the federation push wire pattern: many short
// InsertProof RPCs against many universe servers. It measures the cost
// of the current "fresh dial per call" pattern in
// universe.FederationEnvoy.pushProofToServer against (a) a hand-rolled
// connection pool that establishes the theoretical ceiling, and (b)
// the real rpcserver.UniverseConnPool. The three variants share one
// fixture so their numbers are directly comparable.
//
// The benchmark stands up N real gRPC servers with TLS on loopback.
// Loopback understates the WAN gain (where TLS handshake is multiple
// RTTs), so the numbers here are a lower bound.

package wire

import (
	"context"
	"crypto/tls"
	"fmt"
	"net"
	"sync/atomic"
	"testing"
	"time"

	"github.com/lightninglabs/taproot-assets/rpcserver"
	"github.com/lightninglabs/taproot-assets/taprpc/universerpc"
	"github.com/lightninglabs/taproot-assets/universe"
	"github.com/lightningnetwork/lnd/cert"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

// noopUniverseServer is a minimal UniverseServer implementation that
// answers InsertProof (and Info, in case of probes) with empty
// responses. The benchmark only cares about wire / dial cost — not
// response decode work — so it issues raw InsertProof calls and ignores
// the response.
type noopUniverseServer struct {
	universerpc.UnimplementedUniverseServer
}

func (noopUniverseServer) InsertProof(_ context.Context,
	_ *universerpc.AssetProof) (*universerpc.AssetProofResponse, error) {

	return &universerpc.AssetProofResponse{}, nil
}

func (noopUniverseServer) Info(_ context.Context,
	_ *universerpc.InfoRequest) (*universerpc.InfoResponse, error) {

	return &universerpc.InfoResponse{}, nil
}

// countingListener wraps a net.Listener and increments a counter every
// time Accept returns a new connection. Each new TLS connection
// corresponds to one TLS handshake — the cost we are trying to
// eliminate — so counting accepts on the underlying TCP listener
// stands in for handshake count.
type countingListener struct {
	net.Listener
	accepts *atomic.Int64
}

func (l *countingListener) Accept() (net.Conn, error) {
	c, err := l.Listener.Accept()
	if err == nil {
		l.accepts.Add(1)
	}
	return c, err
}

// fedFixture is N TLS-backed in-process universe servers, plus a
// shared counter of all observed Accept calls across them.
type fedFixture struct {
	addrs   []universe.ServerAddr
	accepts *atomic.Int64
}

func newFedFixture(tb testing.TB, n int) *fedFixture {
	tb.Helper()

	var accepts atomic.Int64
	addrs := make([]universe.ServerAddr, n)
	for i := 0; i < n; i++ {
		addr := startNoopServer(tb, &accepts)
		addrs[i] = universe.NewServerAddrFromStr(addr)
	}
	return &fedFixture{addrs: addrs, accepts: &accepts}
}

// startNoopServer starts a single TLS gRPC universe server on a free
// loopback port and registers cleanup. The Accept-counting wrapper
// lives below TLS so each new TLS connection bumps the counter.
// Returns the server's listen address.
func startNoopServer(tb testing.TB, accepts *atomic.Int64) string {
	tb.Helper()

	rawLis, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(tb, err)

	certBytes, keyBytes, err := cert.GenCertPair(
		"bench autogenerated cert", nil, nil, false, time.Hour,
	)
	require.NoError(tb, err)

	tlsCert, _, err := cert.LoadCertFromBytes(certBytes, keyBytes)
	require.NoError(tb, err)

	tlsConf := cert.TLSConfFromCert(tlsCert)
	tlsConf.NextProtos = []string{"h2"}

	counting := &countingListener{Listener: rawLis, accepts: accepts}
	tlsLis := tls.NewListener(counting, tlsConf)

	srv := grpc.NewServer()
	universerpc.RegisterUniverseServer(srv, noopUniverseServer{})

	go func() { _ = srv.Serve(tlsLis) }()
	tb.Cleanup(func() {
		srv.Stop()
		_ = tlsLis.Close()
	})

	return rawLis.Addr().String()
}

// dialDirect mirrors rpcserver.ConnectUniverse: TLS with skip-verify,
// h2 default credentials, a fresh grpc.ClientConn — used by the
// fresh-dial and hand-pool variants. The real-pool variant goes
// through rpcserver.UniverseConnPool, which internally calls
// rpcserver.ConnectUniverse with the same options.
func dialDirect(tb testing.TB,
	addr string) (*grpc.ClientConn, universerpc.UniverseClient) {

	tb.Helper()

	creds := credentials.NewTLS(&tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"h2"},
	})
	conn, err := grpc.NewClient(addr,
		grpc.WithTransportCredentials(creds),
	)
	require.NoError(tb, err)

	return conn, universerpc.NewUniverseClient(conn)
}

// warm forces the lazy grpc.NewClient to actually establish its
// transport (and thus run the TLS handshake) before measurement.
func warm(tb testing.TB, cli universerpc.UniverseClient) {
	tb.Helper()
	_, err := cli.InsertProof(context.Background(),
		&universerpc.AssetProof{})
	require.NoError(tb, err)
}

// reportAccepts attaches the per-op accept count (≈ per-op TLS
// handshake count) as a custom benchmark metric.
func reportAccepts(b *testing.B, accepts *atomic.Int64) {
	b.Helper()
	b.ReportMetric(
		float64(accepts.Load())/float64(b.N), "handshakes/op",
	)
}

// BenchmarkFederationPushFreshDial measures the cost of the current
// pushProofToServer pattern: every call dials a fresh grpc.ClientConn,
// runs one InsertProof, and closes the conn. The dial / TLS handshake
// happens lazily on the first RPC, so it lands inside the measured
// block.
//
// Expect handshakes/op ≈ 1.
func BenchmarkFederationPushFreshDial(b *testing.B) {
	for _, n := range []int{1, 5, 10} {
		b.Run(fmt.Sprintf("servers=%d", n), func(b *testing.B) {
			f := newFedFixture(b, n)
			ctx := context.Background()
			req := &universerpc.AssetProof{}

			b.ResetTimer()
			b.ReportAllocs()

			for i := 0; i < b.N; i++ {
				addr := f.addrs[i%len(f.addrs)].HostStr()
				conn, cli := dialDirect(b, addr)
				_, err := cli.InsertProof(ctx, req)
				if err != nil {
					b.Fatal(err)
				}
				_ = conn.Close()
			}

			b.StopTimer()
			reportAccepts(b, f.accepts)
		})
	}
}

// BenchmarkFederationPushHandPool measures the steady-state cost of
// the same push pattern when conns are reused: one grpc.ClientConn per
// server, reused across calls. This is the theoretical ceiling that a
// real connection pool can achieve.
//
// Expect handshakes/op ≈ 0 once the accept count is reset post-warmup.
func BenchmarkFederationPushHandPool(b *testing.B) {
	for _, n := range []int{1, 5, 10} {
		b.Run(fmt.Sprintf("servers=%d", n), func(b *testing.B) {
			f := newFedFixture(b, n)
			ctx := context.Background()
			req := &universerpc.AssetProof{}

			conns := make([]*grpc.ClientConn, n)
			clis := make([]universerpc.UniverseClient, n)
			for i, addr := range f.addrs {
				host := addr.HostStr()
				conns[i], clis[i] = dialDirect(b, host)
				warm(b, clis[i])
			}
			b.Cleanup(func() {
				for _, c := range conns {
					_ = c.Close()
				}
			})

			// Reset post-warmup so the metric reflects only
			// steady-state behaviour.
			f.accepts.Store(0)

			b.ResetTimer()
			b.ReportAllocs()

			for i := 0; i < b.N; i++ {
				cli := clis[i%len(clis)]
				_, err := cli.InsertProof(ctx, req)
				if err != nil {
					b.Fatal(err)
				}
			}

			b.StopTimer()
			reportAccepts(b, f.accepts)
		})
	}
}

// BenchmarkFederationPushRealPool drives the actual
// rpcserver.UniverseConnPool against the same fixture. Numbers should
// match (or come very close to) the hand-pool variant; any large gap
// would indicate the real pool is adding overhead the design didn't
// anticipate.
//
// Expect handshakes/op ≈ 0 once the accept count is reset post-warmup.
func BenchmarkFederationPushRealPool(b *testing.B) {
	for _, n := range []int{1, 5, 10} {
		b.Run(fmt.Sprintf("servers=%d", n), func(b *testing.B) {
			f := newFedFixture(b, n)
			ctx := context.Background()
			req := &universerpc.AssetProof{}

			pool := rpcserver.NewUniverseConnPool()
			b.Cleanup(pool.Close)

			// Warm each server's conn so the TLS handshake
			// doesn't land in the measured block.
			for _, addr := range f.addrs {
				c, err := pool.Get(addr)
				require.NoError(b, err)
				_, err = c.InsertProof(ctx, req)
				require.NoError(b, err)
			}

			f.accepts.Store(0)

			b.ResetTimer()
			b.ReportAllocs()

			for i := 0; i < b.N; i++ {
				addr := f.addrs[i%len(f.addrs)]
				c, err := pool.Get(addr)
				if err != nil {
					b.Fatal(err)
				}
				_, err = c.InsertProof(ctx, req)
				if err != nil {
					b.Fatal(err)
				}
			}

			b.StopTimer()
			reportAccepts(b, f.accepts)
		})
	}
}
