name: "Clean up runner disk space"
description: "Removes large, non-essential toolsets to free up disk space on the runner."

runs:
  using: "composite"
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        set -euo pipefail

        echo "Removing large toolsets to free up disk space..."
        echo "Disk space before cleanup:"
        df -h || true

        shopt -s nullglob

        remove_path() {
          local path="$1"
          if [ -e "$path" ] || [ -L "$path" ]; then
            echo "Removing $path"
            sudo rm -rf "$path"
          fi
        }

        # Remove large toolsets and caches.
        remove_path /usr/share/dotnet
        remove_path /usr/local/lib/android
        remove_path /opt/ghc
        remove_path /usr/share/swift
        for path in /usr/local/julia*; do remove_path "$path"; done
        remove_path /opt/hostedtoolcache

        # Remove caches.
        remove_path /usr/local/share/boost
        if [ -n "${AGENT_TOOLSDIRECTORY:-}" ]; then
          remove_path "$AGENT_TOOLSDIRECTORY"
        fi

        # Remove docker images to save space.
        if command -v docker >/dev/null 2>&1; then
          docker image prune -a -f || true
        else
          echo "Docker not available; skipping image prune."
        fi

        # Remove large apt packages when available.
        if command -v apt-get >/dev/null 2>&1; then
          sudo apt-get remove -y \
            '^aspnetcore-.*' \
            '^dotnet-.*' \
            '^llvm-.*' \
            'php.*' \
            '^mongodb-.*' \
            '^mysql-.*' \
            azure-cli \
            google-chrome-stable \
            firefox \
            powershell \
            mono-devel \
            libgl1-mesa-dri 2>/dev/null || true
          sudo apt-get autoremove -y || true
          sudo apt-get clean || true
        else
          echo "apt-get not available; skipping package removals."
        fi

        echo "Disk space after cleanup:"
        df -h || true
