// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transfers.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const AnchoredAssetsByAnchorTxPrefix = `-- name: AnchoredAssetsByAnchorTxPrefix :many
SELECT assets.asset_id,
       genesis_assets.asset_id AS genesis_asset_id,
       script_keys.tweaked_script_key,
       utxos.outpoint
FROM assets
JOIN genesis_assets
  ON assets.genesis_id = genesis_assets.gen_asset_id
JOIN script_keys
  ON assets.script_key_id = script_keys.script_key_id
JOIN managed_utxos utxos
  ON assets.anchor_utxo_id = utxos.utxo_id
WHERE substr(utxos.outpoint, 1, 32) = $1
  AND NOT EXISTS (
      SELECT 1
      FROM passive_assets passives
      JOIN asset_transfers transfers
        ON passives.transfer_id = transfers.id
      JOIN chain_txns txns
        ON transfers.anchor_txn_id = txns.txn_id
      WHERE passives.asset_id = assets.asset_id
        AND txns.txid = $1
  )
`

type AnchoredAssetsByAnchorTxPrefixRow struct {
	AssetID          int64
	GenesisAssetID   []byte
	TweakedScriptKey []byte
	Outpoint         []byte
}

// The assets a receive (or mint) materialized in outputs of the given
// transaction, each with the parts of its proof locator: managed UTXO
// outpoints are stored as txid || index, so a prefix match on the
// txid finds every output of the transaction.
//
// A holding anchored in the transaction's outputs is the
// transaction's materialization — and so this site's to re-stamp and
// to compensate — unless the transaction's own transfer re-anchored
// it there: a passive_assets row of a transfer anchored by this very
// transaction marks a pre-existing holding the transfer carried
// along, which the porter's confirmation re-stamps and the porter's
// abandonment restores to its prior anchor. Only those are excluded.
// A passive row of some other transfer (a successor that staked the
// holding before broadcasting, and whose re-anchor has not yet
// confirmed) does not change what this transaction materialized: the
// holding still goes with it, and the compensation body sheds the
// successor's reference first.
func (q *Queries) AnchoredAssetsByAnchorTxPrefix(ctx context.Context, txid []byte) ([]AnchoredAssetsByAnchorTxPrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, AnchoredAssetsByAnchorTxPrefix, txid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnchoredAssetsByAnchorTxPrefixRow
	for rows.Next() {
		var i AnchoredAssetsByAnchorTxPrefixRow
		if err := rows.Scan(
			&i.AssetID,
			&i.GenesisAssetID,
			&i.TweakedScriptKey,
			&i.Outpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ApplyPendingOutput = `-- name: ApplyPendingOutput :one
WITH spent_asset AS (
    SELECT genesis_id, asset_group_witness_id, script_version
    FROM assets
    WHERE assets.asset_id = $10
)
INSERT INTO assets (
    genesis_id, version, asset_group_witness_id, script_version, lock_time,
    relative_lock_time, script_key_id, anchor_utxo_id, amount,
    split_commitment_root_hash, split_commitment_root_value, spent
) VALUES (
    (SELECT genesis_id FROM spent_asset),
    $1,
    (SELECT asset_group_witness_id FROM spent_asset),
    (SELECT script_version FROM spent_asset),
    $2, $3, $4, $5, $6,
    $7, $8, $9
)
ON CONFLICT (genesis_id, script_key_id, anchor_utxo_id)
    -- This is a NOP, anchor_utxo_id is one of the unique fields that caused the
    -- conflict.
    DO UPDATE SET anchor_utxo_id = EXCLUDED.anchor_utxo_id
RETURNING asset_id
`

type ApplyPendingOutputParams struct {
	AssetVersion             int32
	LockTime                 sql.NullInt32
	RelativeLockTime         sql.NullInt32
	ScriptKeyID              int64
	AnchorUtxoID             sql.NullInt64
	Amount                   int64
	SplitCommitmentRootHash  []byte
	SplitCommitmentRootValue sql.NullInt64
	Spent                    bool
	SpentAssetID             int64
}

func (q *Queries) ApplyPendingOutput(ctx context.Context, arg ApplyPendingOutputParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, ApplyPendingOutput,
		arg.AssetVersion,
		arg.LockTime,
		arg.RelativeLockTime,
		arg.ScriptKeyID,
		arg.AnchorUtxoID,
		arg.Amount,
		arg.SplitCommitmentRootHash,
		arg.SplitCommitmentRootValue,
		arg.Spent,
		arg.SpentAssetID,
	)
	var asset_id int64
	err := row.Scan(&asset_id)
	return asset_id, err
}

const AssetIDsByAnchorTxPrefix = `-- name: AssetIDsByAnchorTxPrefix :many
SELECT assets.asset_id
FROM assets
JOIN managed_utxos utxos
  ON assets.anchor_utxo_id = utxos.utxo_id
WHERE substr(utxos.outpoint, 1, 32) = $1
  AND NOT EXISTS (
      SELECT 1
      FROM passive_assets passives
      WHERE passives.asset_id = assets.asset_id
  )
`

// The assets a receive materialized in outputs of the given
// transaction: managed UTXO outpoints are stored as txid || index, so
// a prefix match on the txid finds every output of the transaction.
//
// Passive assets are excluded. A passive_assets row records that a
// transfer re-anchored a pre-existing holding into one of its own
// outputs, so such an asset is staked by that transfer and is the
// porter's to compensate, not the receive's. Deleting it here would
// destroy a holding the receive never materialized — and, because
// passive_assets.asset_id is a NOT NULL reference to the row being
// deleted, would fail the delivery transaction outright.
func (q *Queries) AssetIDsByAnchorTxPrefix(ctx context.Context, txid []byte) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, AssetIDsByAnchorTxPrefix, txid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var asset_id int64
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const AssetProofBlobByAssetID = `-- name: AssetProofBlobByAssetID :one
SELECT proof_file
FROM asset_proofs
WHERE asset_id = $1
`

// The proof blob keyed by the asset's primary key (not the BIPS
// asset ID), as needed when compensating passive re-anchors.
func (q *Queries) AssetProofBlobByAssetID(ctx context.Context, assetID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, AssetProofBlobByAssetID, assetID)
	var proof_file []byte
	err := row.Scan(&proof_file)
	return proof_file, err
}

const CountLiveTransfersSpendingPoint = `-- name: CountLiveTransfersSpendingPoint :one
SELECT COUNT(DISTINCT transfers.id)
FROM asset_transfers transfers
JOIN asset_transfer_inputs inputs
  ON inputs.transfer_id = transfers.id
JOIN chain_txns txns
  ON txns.txn_id = transfers.anchor_txn_id
WHERE inputs.anchor_point = $1
  AND transfers.id != $2
  AND transfers.superseded = false
  AND txns.block_hash IS NULL
`

type CountLiveTransfersSpendingPointParams struct {
	AnchorPoint         []byte
	AbandonedTransferID int64
}

// The live claimants of an anchor point other than the given
// (abandoned) transfer: unconfirmed transfers, not superseded, that
// spend the point. A revived rival is one — its replacement is still
// in flight to spend the input — so the abandonment retains the
// input's lease rather than releasing it.
func (q *Queries) CountLiveTransfersSpendingPoint(ctx context.Context, arg CountLiveTransfersSpendingPointParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountLiveTransfersSpendingPoint, arg.AnchorPoint, arg.AbandonedTransferID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteAssetByID = `-- name: DeleteAssetByID :exec
DELETE FROM assets
WHERE asset_id = $1
`

func (q *Queries) DeleteAssetByID(ctx context.Context, assetID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAssetByID, assetID)
	return err
}

const DeleteAssetProofByAssetID = `-- name: DeleteAssetProofByAssetID :exec
DELETE FROM asset_proofs
WHERE asset_id = $1
`

func (q *Queries) DeleteAssetProofByAssetID(ctx context.Context, assetID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAssetProofByAssetID, assetID)
	return err
}

const DeleteAssetWitnesses = `-- name: DeleteAssetWitnesses :exec
DELETE FROM asset_witnesses
WHERE asset_id = $1
`

func (q *Queries) DeleteAssetWitnesses(ctx context.Context, assetID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAssetWitnesses, assetID)
	return err
}

const DeleteBurnsByTransferID = `-- name: DeleteBurnsByTransferID :exec
DELETE FROM asset_burn_transfers
WHERE transfer_id = $1
`

func (q *Queries) DeleteBurnsByTransferID(ctx context.Context, transferID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteBurnsByTransferID, transferID)
	return err
}

const DeletePassiveAssetsByAssetID = `-- name: DeletePassiveAssetsByAssetID :execrows
DELETE FROM passive_assets
WHERE asset_id = $1
`

// The passive re-anchor records pointing at one asset row.
//
// A transfer records its intent to re-anchor a pre-existing holding
// before it broadcasts, so an asset that an earlier, confirmed
// transfer materialized as one of its outputs can already be a
// successor's passive holding by the time that earlier transfer is
// abandoned. passive_assets.asset_id is NOT NULL with no ON DELETE, so
// the reference has to be shed before the row it points at; otherwise
// the delete fails the watcher's entire delivery transaction and the
// abandonment can never apply at all.
//
// Discarding the successor's record is the correct reversal rather
// than merely the expedient one. The asset is being erased because the
// transaction that created it is gone from the surviving chain, so the
// successor's re-anchor of it never had a subject — and the successor,
// which spends an anchor output that no longer exists, cannot confirm
// either. The successor's own compensation reads passive_assets by
// transfer and simply finds nothing left to restore.
func (q *Queries) DeletePassiveAssetsByAssetID(ctx context.Context, assetID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeletePassiveAssetsByAssetID, assetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const FetchTransferInputs = `-- name: FetchTransferInputs :many
SELECT input_id, anchor_point, asset_id, script_key, amount
FROM asset_transfer_inputs inputs
WHERE transfer_id = $1
ORDER BY input_id
`

type FetchTransferInputsRow struct {
	InputID     int64
	AnchorPoint []byte
	AssetID     []byte
	ScriptKey   []byte
	Amount      int64
}

func (q *Queries) FetchTransferInputs(ctx context.Context, transferID int64) ([]FetchTransferInputsRow, error) {
	rows, err := q.db.QueryContext(ctx, FetchTransferInputs, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchTransferInputsRow
	for rows.Next() {
		var i FetchTransferInputsRow
		if err := rows.Scan(
			&i.InputID,
			&i.AnchorPoint,
			&i.AssetID,
			&i.ScriptKey,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FetchTransferOutputs = `-- name: FetchTransferOutputs :many
SELECT
    output_id, proof_suffix, amount, serialized_witnesses, script_key_local,
    split_commitment_root_hash, split_commitment_root_value, num_passive_assets,
    output_type, proof_courier_addr, proof_delivery_complete, position,
    asset_version, lock_time, relative_lock_time, tap_address,
    utxos.utxo_id AS anchor_utxo_id,
    utxos.outpoint AS anchor_outpoint,
    utxos.amt_sats AS anchor_value,
    utxos.merkle_root AS anchor_merkle_root,
    utxos.taproot_asset_root AS anchor_taproot_asset_root,
    utxos.tapscript_sibling AS anchor_tapscript_sibling,
    utxos.root_version AS anchor_commitment_version,
    utxo_internal_keys.raw_key AS internal_key_raw_key_bytes,
    utxo_internal_keys.key_family AS internal_key_family,
    utxo_internal_keys.key_index AS internal_key_index,
    script_keys.script_key_id, script_keys.internal_key_id, script_keys.tweaked_script_key, script_keys.tweak, script_keys.key_type,
    script_internal_keys.key_id, script_internal_keys.raw_key, script_internal_keys.key_family, script_internal_keys.key_index
FROM asset_transfer_outputs outputs
JOIN managed_utxos utxos
  ON outputs.anchor_utxo = utxos.utxo_id
JOIN script_keys
  ON outputs.script_key = script_keys.script_key_id
JOIN internal_keys script_internal_keys
  ON script_keys.internal_key_id = script_internal_keys.key_id
JOIN internal_keys utxo_internal_keys
  ON utxos.internal_key_id = utxo_internal_keys.key_id
WHERE transfer_id = $1
ORDER BY output_id
`

type FetchTransferOutputsRow struct {
	OutputID                 int64
	ProofSuffix              []byte
	Amount                   int64
	SerializedWitnesses      []byte
	ScriptKeyLocal           bool
	SplitCommitmentRootHash  []byte
	SplitCommitmentRootValue sql.NullInt64
	NumPassiveAssets         int32
	OutputType               int16
	ProofCourierAddr         []byte
	ProofDeliveryComplete    sql.NullBool
	Position                 int32
	AssetVersion             int32
	LockTime                 sql.NullInt32
	RelativeLockTime         sql.NullInt32
	TapAddress               sql.NullString
	AnchorUtxoID             int64
	AnchorOutpoint           []byte
	AnchorValue              int64
	AnchorMerkleRoot         []byte
	AnchorTaprootAssetRoot   []byte
	AnchorTapscriptSibling   []byte
	AnchorCommitmentVersion  sql.NullInt16
	InternalKeyRawKeyBytes   []byte
	InternalKeyFamily        int32
	InternalKeyIndex         int32
	ScriptKey                ScriptKey
	InternalKey              InternalKey
}

func (q *Queries) FetchTransferOutputs(ctx context.Context, transferID int64) ([]FetchTransferOutputsRow, error) {
	rows, err := q.db.QueryContext(ctx, FetchTransferOutputs, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchTransferOutputsRow
	for rows.Next() {
		var i FetchTransferOutputsRow
		if err := rows.Scan(
			&i.OutputID,
			&i.ProofSuffix,
			&i.Amount,
			&i.SerializedWitnesses,
			&i.ScriptKeyLocal,
			&i.SplitCommitmentRootHash,
			&i.SplitCommitmentRootValue,
			&i.NumPassiveAssets,
			&i.OutputType,
			&i.ProofCourierAddr,
			&i.ProofDeliveryComplete,
			&i.Position,
			&i.AssetVersion,
			&i.LockTime,
			&i.RelativeLockTime,
			&i.TapAddress,
			&i.AnchorUtxoID,
			&i.AnchorOutpoint,
			&i.AnchorValue,
			&i.AnchorMerkleRoot,
			&i.AnchorTaprootAssetRoot,
			&i.AnchorTapscriptSibling,
			&i.AnchorCommitmentVersion,
			&i.InternalKeyRawKeyBytes,
			&i.InternalKeyFamily,
			&i.InternalKeyIndex,
			&i.ScriptKey.ScriptKeyID,
			&i.ScriptKey.InternalKeyID,
			&i.ScriptKey.TweakedScriptKey,
			&i.ScriptKey.Tweak,
			&i.ScriptKey.KeyType,
			&i.InternalKey.KeyID,
			&i.InternalKey.RawKey,
			&i.InternalKey.KeyFamily,
			&i.InternalKey.KeyIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertAssetTransfer = `-- name: InsertAssetTransfer :one
WITH target_txn(txn_id) AS (
    SELECT txn_id
    FROM chain_txns
    WHERE txid = $5
)
INSERT INTO asset_transfers (
    height_hint, anchor_txn_id, transfer_time_unix, label,
    skip_anchor_tx_broadcast
) VALUES (
    $1, (SELECT txn_id FROM target_txn), $2, $3,
    $4
) RETURNING id
`

type InsertAssetTransferParams struct {
	HeightHint            int32
	TransferTimeUnix      time.Time
	Label                 sql.NullString
	SkipAnchorTxBroadcast bool
	AnchorTxid            []byte
}

func (q *Queries) InsertAssetTransfer(ctx context.Context, arg InsertAssetTransferParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertAssetTransfer,
		arg.HeightHint,
		arg.TransferTimeUnix,
		arg.Label,
		arg.SkipAnchorTxBroadcast,
		arg.AnchorTxid,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertAssetTransferInput = `-- name: InsertAssetTransferInput :exec
INSERT INTO asset_transfer_inputs (
    transfer_id, anchor_point, asset_id, script_key, amount
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertAssetTransferInputParams struct {
	TransferID  int64
	AnchorPoint []byte
	AssetID     []byte
	ScriptKey   []byte
	Amount      int64
}

func (q *Queries) InsertAssetTransferInput(ctx context.Context, arg InsertAssetTransferInputParams) error {
	_, err := q.db.ExecContext(ctx, InsertAssetTransferInput,
		arg.TransferID,
		arg.AnchorPoint,
		arg.AssetID,
		arg.ScriptKey,
		arg.Amount,
	)
	return err
}

const InsertAssetTransferOutput = `-- name: InsertAssetTransferOutput :exec
INSERT INTO asset_transfer_outputs (
    transfer_id, anchor_utxo, script_key, script_key_local,
    amount, serialized_witnesses, split_commitment_root_hash,
    split_commitment_root_value, proof_suffix, num_passive_assets,
    output_type, proof_courier_addr, asset_version, lock_time,
    relative_lock_time, proof_delivery_complete, position, tap_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18
)
`

type InsertAssetTransferOutputParams struct {
	TransferID               int64
	AnchorUtxo               int64
	ScriptKey                int64
	ScriptKeyLocal           bool
	Amount                   int64
	SerializedWitnesses      []byte
	SplitCommitmentRootHash  []byte
	SplitCommitmentRootValue sql.NullInt64
	ProofSuffix              []byte
	NumPassiveAssets         int32
	OutputType               int16
	ProofCourierAddr         []byte
	AssetVersion             int32
	LockTime                 sql.NullInt32
	RelativeLockTime         sql.NullInt32
	ProofDeliveryComplete    sql.NullBool
	Position                 int32
	TapAddress               sql.NullString
}

func (q *Queries) InsertAssetTransferOutput(ctx context.Context, arg InsertAssetTransferOutputParams) error {
	_, err := q.db.ExecContext(ctx, InsertAssetTransferOutput,
		arg.TransferID,
		arg.AnchorUtxo,
		arg.ScriptKey,
		arg.ScriptKeyLocal,
		arg.Amount,
		arg.SerializedWitnesses,
		arg.SplitCommitmentRootHash,
		arg.SplitCommitmentRootValue,
		arg.ProofSuffix,
		arg.NumPassiveAssets,
		arg.OutputType,
		arg.ProofCourierAddr,
		arg.AssetVersion,
		arg.LockTime,
		arg.RelativeLockTime,
		arg.ProofDeliveryComplete,
		arg.Position,
		arg.TapAddress,
	)
	return err
}

const InsertBurn = `-- name: InsertBurn :one
INSERT INTO asset_burn_transfers (
    transfer_id, note, asset_id, group_key, amount
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING burn_id
`

type InsertBurnParams struct {
	TransferID int64
	Note       sql.NullString
	AssetID    []byte
	GroupKey   []byte
	Amount     int64
}

func (q *Queries) InsertBurn(ctx context.Context, arg InsertBurnParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertBurn,
		arg.TransferID,
		arg.Note,
		arg.AssetID,
		arg.GroupKey,
		arg.Amount,
	)
	var burn_id int64
	err := row.Scan(&burn_id)
	return burn_id, err
}

const InsertPassiveAsset = `-- name: InsertPassiveAsset :exec
WITH target_asset(asset_id) AS (
    SELECT assets.asset_id
    FROM assets
        JOIN genesis_assets
            ON assets.genesis_id = genesis_assets.gen_asset_id
        JOIN managed_utxos utxos
            ON assets.anchor_utxo_id = utxos.utxo_id
        JOIN script_keys
            ON assets.script_key_id = script_keys.script_key_id
    WHERE genesis_assets.asset_id = $7
        AND utxos.outpoint = $8
        AND script_keys.tweaked_script_key = $3
)
INSERT INTO passive_assets (
    asset_id, transfer_id, new_anchor_utxo, script_key, new_witness_stack,
    new_proof, asset_version
) VALUES (
    (SELECT asset_id FROM target_asset), $1, $2,
    $3, $4, $5, $6
)
`

type InsertPassiveAssetParams struct {
	TransferID      int64
	NewAnchorUtxo   int64
	ScriptKey       []byte
	NewWitnessStack []byte
	NewProof        []byte
	AssetVersion    int32
	AssetGenesisID  []byte
	PrevOutpoint    []byte
}

func (q *Queries) InsertPassiveAsset(ctx context.Context, arg InsertPassiveAssetParams) error {
	_, err := q.db.ExecContext(ctx, InsertPassiveAsset,
		arg.TransferID,
		arg.NewAnchorUtxo,
		arg.ScriptKey,
		arg.NewWitnessStack,
		arg.NewProof,
		arg.AssetVersion,
		arg.AssetGenesisID,
		arg.PrevOutpoint,
	)
	return err
}

const LogProofTransferAttempt = `-- name: LogProofTransferAttempt :exec
INSERT INTO proof_transfer_log (
    transfer_type, proof_locator_hash, time_unix
) VALUES (
    $1, $2, $3
)
`

type LogProofTransferAttemptParams struct {
	TransferType     string
	ProofLocatorHash []byte
	TimeUnix         time.Time
}

func (q *Queries) LogProofTransferAttempt(ctx context.Context, arg LogProofTransferAttemptParams) error {
	_, err := q.db.ExecContext(ctx, LogProofTransferAttempt, arg.TransferType, arg.ProofLocatorHash, arg.TimeUnix)
	return err
}

const MarkTransferSuperseded = `-- name: MarkTransferSuperseded :exec
UPDATE asset_transfers
SET superseded = true, abandoned = true
WHERE id = $1
`

// An abandoned transfer is permanently dead: its anchor inputs were
// claimed by a buried foreign transaction, so its own anchor can
// never confirm. Superseded transfers are not resumed at startup.
//
// The abandoned flag records *why* it is superseded, so that a later
// abandonment of a sibling sharing an input cannot revive it.
func (q *Queries) MarkTransferSuperseded(ctx context.Context, transferID int64) error {
	_, err := q.db.ExecContext(ctx, MarkTransferSuperseded, transferID)
	return err
}

const QueryAssetTransfers = `-- name: QueryAssetTransfers :many
SELECT
    id, height_hint, txns.txid, txns.block_hash AS anchor_tx_block_hash,
    transfer_time_unix, transfers.label,
    transfers.skip_anchor_tx_broadcast
FROM asset_transfers transfers
JOIN chain_txns txns
    ON txns.txn_id = transfers.anchor_txn_id
WHERE
    -- Optionally filter on a given anchor_tx_hash.
    (txns.txid = $1
        OR $1 IS NULL)

    -- Filter for pending transfers only if requested.
    --
    -- NOTE: This query is also executed by programmatic migrations against
    -- historical schema versions, so it MUST NOT reference columns added
    -- in later migrations (such as transfers.superseded). Superseded
    -- transfers are filtered out in Go instead.
    AND (
        $2 = true AND
        (
            txns.block_hash IS NULL
                OR EXISTS (
                    SELECT 1
                    FROM asset_transfer_outputs outputs
                    WHERE outputs.transfer_id = transfers.id
                      AND outputs.proof_delivery_complete = false
                )
        )
        OR $2 = false OR $2 IS NULL
    )

    -- Optionally filter on a given start time.
    AND transfers.transfer_time_unix >=
        COALESCE($3, transfers.transfer_time_unix)

    -- Optionally filter on a given label.
    AND (transfers.label = $4 OR
            $4 IS NULL)

    -- Optionally filter on outputs with a specific script key.
    AND (
      EXISTS (
        SELECT 1
        FROM asset_transfer_outputs outputs
        JOIN script_keys sk ON outputs.script_key = sk.script_key_id
        WHERE outputs.transfer_id = transfers.id
          AND sk.tweaked_script_key = $5
      )
      OR $5 IS NULL
    )
ORDER BY transfer_time_unix
`

type QueryAssetTransfersParams struct {
	AnchorTxHash         []byte
	PendingTransfersOnly interface{}
	StartTime            sql.NullTime
	FilterLabel          sql.NullString
	FilterScriptKey      []byte
}

type QueryAssetTransfersRow struct {
	ID                    int64
	HeightHint            int32
	Txid                  []byte
	AnchorTxBlockHash     []byte
	TransferTimeUnix      time.Time
	Label                 sql.NullString
	SkipAnchorTxBroadcast bool
}

func (q *Queries) QueryAssetTransfers(ctx context.Context, arg QueryAssetTransfersParams) ([]QueryAssetTransfersRow, error) {
	rows, err := q.db.QueryContext(ctx, QueryAssetTransfers,
		arg.AnchorTxHash,
		arg.PendingTransfersOnly,
		arg.StartTime,
		arg.FilterLabel,
		arg.FilterScriptKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAssetTransfersRow
	for rows.Next() {
		var i QueryAssetTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.HeightHint,
			&i.Txid,
			&i.AnchorTxBlockHash,
			&i.TransferTimeUnix,
			&i.Label,
			&i.SkipAnchorTxBroadcast,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QueryBurns = `-- name: QueryBurns :many
SELECT
    abt.note,
    abt.asset_id,
    abt.group_key,
    ga.asset_type,
    abt.amount,
    ct.txid AS anchor_txid -- Retrieving the txid from chain_txns.
FROM asset_burn_transfers abt
JOIN genesis_assets ga ON abt.asset_id = ga.asset_id
JOIN asset_transfers at ON abt.transfer_id = at.id
JOIN chain_txns ct ON at.anchor_txn_id = ct.txn_id
WHERE
    -- Optionally filter by asset_id.
    (abt.asset_id = $1 OR $1 IS NULL)

    -- Optionally filter by group_key.
    AND (abt.group_key = $2 OR $2 IS NULL)

    -- Optionally filter by anchor_txid in chain_txns.txid.
    AND (ct.txid = $3 OR $3 IS NULL)
ORDER BY abt.burn_id
`

type QueryBurnsParams struct {
	AssetID    []byte
	GroupKey   []byte
	AnchorTxid []byte
}

type QueryBurnsRow struct {
	Note       sql.NullString
	AssetID    []byte
	GroupKey   []byte
	AssetType  int16
	Amount     int64
	AnchorTxid []byte
}

func (q *Queries) QueryBurns(ctx context.Context, arg QueryBurnsParams) ([]QueryBurnsRow, error) {
	rows, err := q.db.QueryContext(ctx, QueryBurns, arg.AssetID, arg.GroupKey, arg.AnchorTxid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryBurnsRow
	for rows.Next() {
		var i QueryBurnsRow
		if err := rows.Scan(
			&i.Note,
			&i.AssetID,
			&i.GroupKey,
			&i.AssetType,
			&i.Amount,
			&i.AnchorTxid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QueryPassiveAssets = `-- name: QueryPassiveAssets :many
SELECT passive.asset_id, passive.new_anchor_utxo, passive.script_key,
       passive.new_witness_stack, passive.new_proof,
       genesis_assets.asset_id AS genesis_id, passive.asset_version,
       utxos.outpoint
FROM passive_assets as passive
    JOIN assets
        ON passive.asset_id = assets.asset_id
    JOIN genesis_assets
        ON assets.genesis_id = genesis_assets.gen_asset_id
    JOIN managed_utxos utxos
        ON passive.new_anchor_utxo = utxos.utxo_id
WHERE passive.transfer_id = $1
`

type QueryPassiveAssetsRow struct {
	AssetID         int64
	NewAnchorUtxo   int64
	ScriptKey       []byte
	NewWitnessStack []byte
	NewProof        []byte
	GenesisID       []byte
	AssetVersion    int32
	Outpoint        []byte
}

func (q *Queries) QueryPassiveAssets(ctx context.Context, transferID int64) ([]QueryPassiveAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, QueryPassiveAssets, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryPassiveAssetsRow
	for rows.Next() {
		var i QueryPassiveAssetsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.NewAnchorUtxo,
			&i.ScriptKey,
			&i.NewWitnessStack,
			&i.NewProof,
			&i.GenesisID,
			&i.AssetVersion,
			&i.Outpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QueryProofTransferAttempts = `-- name: QueryProofTransferAttempts :many
SELECT time_unix
FROM proof_transfer_log
WHERE proof_locator_hash = $1
    AND transfer_type = $2
ORDER BY time_unix DESC
`

type QueryProofTransferAttemptsParams struct {
	ProofLocatorHash []byte
	TransferType     string
}

func (q *Queries) QueryProofTransferAttempts(ctx context.Context, arg QueryProofTransferAttemptsParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, QueryProofTransferAttempts, arg.ProofLocatorHash, arg.TransferType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var time_unix time.Time
		if err := rows.Scan(&time_unix); err != nil {
			return nil, err
		}
		items = append(items, time_unix)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QuerySupersededTransferIDs = `-- name: QuerySupersededTransferIDs :many
SELECT id
FROM asset_transfers
WHERE superseded = true
`

func (q *Queries) QuerySupersededTransferIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, QuerySupersededTransferIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ReAnchorPassiveAssets = `-- name: ReAnchorPassiveAssets :exec
UPDATE assets
SET anchor_utxo_id = $1,
    -- The following fields need to be the same fields we reset in
    -- Asset.CopySpendTemplate.
    split_commitment_root_hash = NULL,
    split_commitment_root_value = NULL,
    lock_time = 0,
    relative_lock_time = 0
WHERE asset_id = $2
`

type ReAnchorPassiveAssetsParams struct {
	NewAnchorUtxoID sql.NullInt64
	AssetID         int64
}

func (q *Queries) ReAnchorPassiveAssets(ctx context.Context, arg ReAnchorPassiveAssetsParams) error {
	_, err := q.db.ExecContext(ctx, ReAnchorPassiveAssets, arg.NewAnchorUtxoID, arg.AssetID)
	return err
}

const RestoreAssetSpendTemplate = `-- name: RestoreAssetSpendTemplate :exec
UPDATE assets
SET anchor_utxo_id = $1,
    split_commitment_root_hash = $2,
    split_commitment_root_value = $3,
    lock_time = $4,
    relative_lock_time = $5
WHERE asset_id = $6
`

type RestoreAssetSpendTemplateParams struct {
	AnchorUtxoID             sql.NullInt64
	SplitCommitmentRootHash  []byte
	SplitCommitmentRootValue sql.NullInt64
	LockTime                 sql.NullInt32
	RelativeLockTime         sql.NullInt32
	AssetID                  int64
}

// The inverse of ReAnchorPassiveAssets: restore the anchor UTXO and
// the spend-template fields that the re-anchor reset.
func (q *Queries) RestoreAssetSpendTemplate(ctx context.Context, arg RestoreAssetSpendTemplateParams) error {
	_, err := q.db.ExecContext(ctx, RestoreAssetSpendTemplate,
		arg.AnchorUtxoID,
		arg.SplitCommitmentRootHash,
		arg.SplitCommitmentRootValue,
		arg.LockTime,
		arg.RelativeLockTime,
		arg.AssetID,
	)
	return err
}

const SetTransferOutputProofDeliveryStatus = `-- name: SetTransferOutputProofDeliveryStatus :exec
WITH target(output_id) AS (
    SELECT output_id
    FROM asset_transfer_outputs output
    JOIN managed_utxos
      ON output.anchor_utxo = managed_utxos.utxo_id
    WHERE managed_utxos.outpoint = $2
      AND output.position = $3
)
UPDATE asset_transfer_outputs
SET proof_delivery_complete = $1
WHERE output_id = (SELECT output_id FROM target)
`

type SetTransferOutputProofDeliveryStatusParams struct {
	DeliveryComplete         sql.NullBool
	SerializedAnchorOutpoint []byte
	Position                 int32
}

func (q *Queries) SetTransferOutputProofDeliveryStatus(ctx context.Context, arg SetTransferOutputProofDeliveryStatusParams) error {
	_, err := q.db.ExecContext(ctx, SetTransferOutputProofDeliveryStatus, arg.DeliveryComplete, arg.SerializedAnchorOutpoint, arg.Position)
	return err
}

const SupersedeConflictingTransfers = `-- name: SupersedeConflictingTransfers :execrows
UPDATE asset_transfers
SET superseded = true
WHERE id != $1
  AND superseded = false
  AND id IN (
      SELECT inputs.transfer_id
      FROM asset_transfer_inputs inputs
      WHERE inputs.anchor_point = $2
  )
  AND anchor_txn_id IN (
      SELECT txns.txn_id
      FROM chain_txns txns
      WHERE txns.block_hash IS NULL
  )
`

type SupersedeConflictingTransfersParams struct {
	ConfirmedTransferID int64
	AnchorPoint         []byte
}

// Mark all unconfirmed transfers that spend the given anchor point as
// superseded, except for the given (just confirmed) transfer. Once a
// conflicting transfer has confirmed on-chain, these transfers' anchor
// transactions can never confirm.
func (q *Queries) SupersedeConflictingTransfers(ctx context.Context, arg SupersedeConflictingTransfersParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, SupersedeConflictingTransfers, arg.ConfirmedTransferID, arg.AnchorPoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SupersedeIfConflictingConfirmed = `-- name: SupersedeIfConflictingConfirmed :exec
UPDATE asset_transfers
SET superseded = true
WHERE asset_transfers.anchor_txn_id = (
      SELECT anchor.txn_id
      FROM chain_txns anchor
      WHERE anchor.txid = $1
  )
  AND EXISTS (
      SELECT 1
      FROM asset_transfer_inputs own_in
      JOIN asset_transfer_inputs other_in
        ON other_in.anchor_point = own_in.anchor_point
       AND other_in.transfer_id != own_in.transfer_id
      JOIN asset_transfers other
        ON other.id = other_in.transfer_id
      JOIN chain_txns txns
        ON txns.txn_id = other.anchor_txn_id
      WHERE own_in.transfer_id = asset_transfers.id
        AND txns.block_hash IS NOT NULL
  )
`

// Re-enter supersession for the transfer of the given anchor
// transaction when another confirmed transfer claims one of its
// inputs, applied when its confirmation is withdrawn. The rival's
// confirmation did not supersede this transfer — only unconfirmed
// rivals are superseded, and this one was confirmed at the time — so
// without this it would sit unconfirmed and unsuperseded, be resumed
// at startup, and rebroadcast an anchor that can never confirm.
func (q *Queries) SupersedeIfConflictingConfirmed(ctx context.Context, txid []byte) error {
	_, err := q.db.ExecContext(ctx, SupersedeIfConflictingConfirmed, txid)
	return err
}

const SupersededTransfersSpendingPoint = `-- name: SupersededTransfersSpendingPoint :many
SELECT DISTINCT transfers.id
FROM asset_transfers transfers
JOIN asset_transfer_inputs inputs
  ON inputs.transfer_id = transfers.id
WHERE inputs.anchor_point = $1
  AND transfers.id != $2
  AND transfers.superseded = true
  AND transfers.abandoned = false
ORDER BY transfers.id
`

type SupersededTransfersSpendingPointParams struct {
	AnchorPoint         []byte
	AbandonedTransferID int64
}

// The superseded rivals of an abandoned transfer at one of its anchor
// points: the candidates for revival when it is abandoned.
//
// Only rivalry losers are candidates. A transfer marked abandoned was
// superseded by its own abandonment — its inputs were claimed by a
// buried foreign transaction — so reviving it would resume a transfer
// whose anchor can never confirm.
func (q *Queries) SupersededTransfersSpendingPoint(ctx context.Context, arg SupersededTransfersSpendingPointParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, SupersededTransfersSpendingPoint, arg.AnchorPoint, arg.AbandonedTransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TransferOutputAssetID = `-- name: TransferOutputAssetID :one
SELECT assets.asset_id
FROM assets
JOIN genesis_assets
    ON assets.genesis_id = genesis_assets.gen_asset_id
WHERE assets.script_key_id = $1
  AND assets.anchor_utxo_id = $2
  AND genesis_assets.asset_id = $3
`

type TransferOutputAssetIDParams struct {
	ScriptKeyID  int64
	AnchorUtxoID sql.NullInt64
	AssetID      []byte
}

// The asset row a transfer output materialized into, if any: the
// convergence guard for re-applying a confirmation, and the target
// of compensation when the transfer is abandoned. The genesis filter
// is necessary: distinct assets can share both script key and anchor
// UTXO (a multi-asset HTLC swept in one transaction), so the pair
// alone is ambiguous.
func (q *Queries) TransferOutputAssetID(ctx context.Context, arg TransferOutputAssetIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, TransferOutputAssetID, arg.ScriptKeyID, arg.AnchorUtxoID, arg.AssetID)
	var asset_id int64
	err := row.Scan(&asset_id)
	return asset_id, err
}

const UnconfirmChainAnchorTx = `-- name: UnconfirmChainAnchorTx :exec
UPDATE chain_txns
SET block_hash = NULL, block_height = NULL, tx_index = NULL
WHERE txid = $1
`

// The inverse of ConfirmChainAnchorTx: the anchor transaction's
// recorded confirmation is withdrawn (its block was re-organized
// away and nothing has replaced it yet).
func (q *Queries) UnconfirmChainAnchorTx(ctx context.Context, txid []byte) error {
	_, err := q.db.ExecContext(ctx, UnconfirmChainAnchorTx, txid)
	return err
}

const UnsupersedeSafeTransfer = `-- name: UnsupersedeSafeTransfer :execrows
UPDATE asset_transfers
SET superseded = false
WHERE asset_transfers.id = $1
  AND asset_transfers.superseded = true
  AND asset_transfers.abandoned = false
  AND NOT EXISTS (
      SELECT 1
      FROM asset_transfer_inputs own_in
      JOIN asset_transfer_inputs other_in
        ON other_in.anchor_point = own_in.anchor_point
       AND other_in.transfer_id != own_in.transfer_id
      JOIN asset_transfers other
        ON other.id = other_in.transfer_id
      JOIN chain_txns txns
        ON txns.txn_id = other.anchor_txn_id
      WHERE own_in.transfer_id = $1
        AND txns.block_hash IS NOT NULL
  )
`

// The inverse of SupersedeConflictingTransfers for one rivalry loser,
// applied when the transfer that superseded it is abandoned: the loser
// becomes live again, provided no confirmed transfer conflicts with it
// on any of its inputs — not merely on the input it shared with the
// abandoned transfer. A rival that also spends an input some other
// confirmed transfer claims can never confirm, and reviving it would
// resume a parcel that rebroadcasts a doomed anchor.
//
// The abandoned transfer's own confirmation is withdrawn before this
// runs, so it cannot answer as the conflicting claimant.
func (q *Queries) UnsupersedeSafeTransfer(ctx context.Context, transferID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, UnsupersedeSafeTransfer, transferID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UnsupersedeTransfer = `-- name: UnsupersedeTransfer :exec
UPDATE asset_transfers
SET superseded = false
WHERE id = $1
  AND abandoned = false
`

// Lift the confirming transfer's own superseded flag. A rivalry loser
// can still confirm — the rival that superseded it may since have been
// re-organized out — and once it does, its confirmation supersedes the
// rival in turn; the flag on the transfer itself must be lifted too,
// or it is skipped at startup and never completes. An abandoned
// transfer is left alone: it was compensated by its own abandonment.
func (q *Queries) UnsupersedeTransfer(ctx context.Context, transferID int64) error {
	_, err := q.db.ExecContext(ctx, UnsupersedeTransfer, transferID)
	return err
}

const UnsweepManagedUTXOsByTxid = `-- name: UnsweepManagedUTXOsByTxid :exec
UPDATE managed_utxos
SET swept_txn_id = NULL
WHERE swept_txn_id = (
    SELECT txn_id FROM chain_txns WHERE txid = $1
)
`

// The inverse of MarkManagedUTXOAsSwept for every UTXO swept by the
// given (now abandoned) transaction.
func (q *Queries) UnsweepManagedUTXOsByTxid(ctx context.Context, txid []byte) error {
	_, err := q.db.ExecContext(ctx, UnsweepManagedUTXOsByTxid, txid)
	return err
}
