package test

import (
	"crypto/tls"
	"fmt"
	"net"
	"sync"
	"testing"
	"time"

	"github.com/lightningnetwork/lnd/cert"
	"github.com/lightningnetwork/lnd/lntest/port"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc"
)

var (
	// ListenAddrTemplate is the template for the address the mock server
	// listens on.
	ListenAddrTemplate = "localhost:%d"

	// StartupWaitTime is the time we wait for the server to start up.
	StartupWaitTime = 50 * time.Millisecond
)

// StartMockGRPCServer starts a mock gRPC server on a free port and returns the
// address it's listening on. The caller should clean up the server by calling
// the cleanup function.
func StartMockGRPCServer(t *testing.T, grpcServer *grpc.Server,
	withTLS bool) (string, func(), error) {

	nextPort := port.NextAvailablePort()
	listenAddr := fmt.Sprintf(ListenAddrTemplate, nextPort)

	grpcListener, err := net.Listen("tcp", listenAddr)
	if err != nil {
		return "", nil, fmt.Errorf("mock RPC server unable to listen "+
			"on %s", listenAddr)
	}

	var listener net.Listener = grpcListener
	if withTLS {
		listener = tls.NewListener(grpcListener, genCert(t))
	}

	var (
		wg             sync.WaitGroup
		started        = make(chan struct{})
		startupErrChan = make(chan error, 1)
	)
	wg.Add(1)
	go func() {
		defer wg.Done()

		// The goroutine has started, signal the main goroutine.
		close(started)

		err := grpcServer.Serve(listener)
		if err != nil {
			startupErrChan <- fmt.Errorf("mock RPC server unable "+
				"to serve on %s: %v", listenAddr, err)
		}

		close(startupErrChan)
	}()

	// We wait until the goroutine has started before returning the
	// listener address.
	<-started

	// If we get an error during startup, we return it immediately. If we
	// don't get an error now, it means the server has started successfully.
	// Any errors during the server's lifetime will be swallowed though.
	startupWait := time.After(StartupWaitTime)
	select {
	case err := <-startupErrChan:
		return "", nil, err
	case <-startupWait:
	}

	cleanup := func() {
		grpcServer.Stop()
		_ = grpcListener.Close()
		wg.Wait()
	}

	return listenAddr, cleanup, nil
}

func genCert(t *testing.T) *tls.Config {
	certBytes, keyBytes, err := cert.GenCertPair(
		"tapd autogenerated cert", nil, nil, false, time.Minute,
	)
	require.NoError(t, err)

	tlsCert, _, err := cert.LoadCertFromBytes(certBytes, keyBytes)
	require.NoError(t, err)

	return cert.TLSConfFromCert(tlsCert)
}
