// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: portfoliopilotrpc/portfolio_pilot.proto

package portfoliopilotrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssetTransferDirection represents the direction of an asset transfer from
// our perspective for pricing and rate queries.
type AssetTransferDirection int32

const (
	// ASSET_TRANSFER_DIRECTION_UNSPECIFIED indicates an unspecified direction.
	AssetTransferDirection_ASSET_TRANSFER_DIRECTION_UNSPECIFIED AssetTransferDirection = 0
	// ASSET_TRANSFER_DIRECTION_BUY indicates we want to buy the asset.
	AssetTransferDirection_ASSET_TRANSFER_DIRECTION_BUY AssetTransferDirection = 1
	// ASSET_TRANSFER_DIRECTION_SELL indicates we want to sell the asset.
	AssetTransferDirection_ASSET_TRANSFER_DIRECTION_SELL AssetTransferDirection = 2
)

// Enum value maps for AssetTransferDirection.
var (
	AssetTransferDirection_name = map[int32]string{
		0: "ASSET_TRANSFER_DIRECTION_UNSPECIFIED",
		1: "ASSET_TRANSFER_DIRECTION_BUY",
		2: "ASSET_TRANSFER_DIRECTION_SELL",
	}
	AssetTransferDirection_value = map[string]int32{
		"ASSET_TRANSFER_DIRECTION_UNSPECIFIED": 0,
		"ASSET_TRANSFER_DIRECTION_BUY":         1,
		"ASSET_TRANSFER_DIRECTION_SELL":        2,
	}
)

func (x AssetTransferDirection) Enum() *AssetTransferDirection {
	p := new(AssetTransferDirection)
	*p = x
	return p
}

func (x AssetTransferDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetTransferDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[0].Descriptor()
}

func (AssetTransferDirection) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[0]
}

func (x AssetTransferDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetTransferDirection.Descriptor instead.
func (AssetTransferDirection) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{0}
}

// Intent is an enum informing the portfolio pilot about the intent of the
// price rate query. This is used to provide context for the asset rates being
// requested, allowing the pilot to tailor the response based on the specific
// use case, such as paying an invoice or receiving a payment and the different
// stages involved in those.
type Intent int32

const (
	// INTENT_UNSPECIFIED is used to indicate that the intent of the price rate
	// query is not specified. This is the fallback default value and should not
	// be used in production code. It is primarily used for backward
	// compatibility with older versions of the protocol that did not include
	// intent information.
	Intent_INTENT_UNSPECIFIED Intent = 0
	// INTENT_PAY_INVOICE_HINT is used to indicate that the user is requesting
	// a price rate hint for paying an invoice. This is typically used by the
	// payer of an invoice to provide a suggestion of the expected asset rate to
	// the RFQ peer (edge node) that will determine the actual rate for the
	// payment.
	Intent_INTENT_PAY_INVOICE_HINT Intent = 1
	// INTENT_PAY_INVOICE is used to indicate that a peer wants to pay an
	// invoice with assets. This is typically used by the edge node that
	// facilitates the swap from assets to BTC for the payer of an invoice. This
	// intent is used to provide the actual asset rate for the payment, which
	// may differ from the hint provided by the payer.
	Intent_INTENT_PAY_INVOICE Intent = 2
	// INTENT_PAY_INVOICE_QUALIFY is used to indicate that the payer of an
	// invoice has received an asset rate from their RFQ peer (edge node) and is
	// qualifying the rate for the payment. This is typically used by the payer
	// of an invoice to ensure that the asset rate provided by their peer (edge
	// node) is acceptable before proceeding with the payment.
	Intent_INTENT_PAY_INVOICE_QUALIFY Intent = 3
	// INTENT_RECV_PAYMENT_HINT is used to indicate that the user is requesting
	// a price rate hint for receiving a payment through an invoice. This is
	// typically used by the creator of an invoice to provide a suggestion of
	// the expected asset rate to the RFQ peer (edge node) that will determine
	// the actual rate used for creating an invoice.
	Intent_INTENT_RECV_PAYMENT_HINT Intent = 4
	// INTENT_RECV_PAYMENT is used to indicate that a peer wants to create an
	// invoice to receive a payment with assets. This is typically used by the
	// edge node that facilitates the swap from BTC to assets for the receiver
	// of a payment. This intent is used to provide the actual asset rate for
	// the invoice creation, which may differ from the hint provided by the
	// receiver.
	Intent_INTENT_RECV_PAYMENT Intent = 5
	// INTENT_RECV_PAYMENT_QUALIFY is used to indicate that the creator of an
	// invoice received an asset rate from their RFQ peer (edge node) and is
	// qualifying the rate for the creation of the invoice. This is typically
	// used by the creator of an invoice to ensure that the asset rate provided
	// by their peer (edge node) is acceptable before proceeding with creating
	// the invoice.
	Intent_INTENT_RECV_PAYMENT_QUALIFY Intent = 6
)

// Enum value maps for Intent.
var (
	Intent_name = map[int32]string{
		0: "INTENT_UNSPECIFIED",
		1: "INTENT_PAY_INVOICE_HINT",
		2: "INTENT_PAY_INVOICE",
		3: "INTENT_PAY_INVOICE_QUALIFY",
		4: "INTENT_RECV_PAYMENT_HINT",
		5: "INTENT_RECV_PAYMENT",
		6: "INTENT_RECV_PAYMENT_QUALIFY",
	}
	Intent_value = map[string]int32{
		"INTENT_UNSPECIFIED":          0,
		"INTENT_PAY_INVOICE_HINT":     1,
		"INTENT_PAY_INVOICE":          2,
		"INTENT_PAY_INVOICE_QUALIFY":  3,
		"INTENT_RECV_PAYMENT_HINT":    4,
		"INTENT_RECV_PAYMENT":         5,
		"INTENT_RECV_PAYMENT_QUALIFY": 6,
	}
)

func (x Intent) Enum() *Intent {
	p := new(Intent)
	*p = x
	return p
}

func (x Intent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Intent) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[1].Descriptor()
}

func (Intent) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[1]
}

func (x Intent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Intent.Descriptor instead.
func (Intent) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{1}
}

// RejectCode represents the possible error codes that can be returned in a
// ResolveRequestResponse reject result.
type RejectCode int32

const (
	// REJECT_CODE_UNSPECIFIED indicates an unspecified error.
	RejectCode_REJECT_CODE_UNSPECIFIED RejectCode = 0
	// REJECT_CODE_PRICE_ORACLE_UNAVAILABLE indicates that pricing could not be
	// provided due to an unavailable oracle.
	RejectCode_REJECT_CODE_PRICE_ORACLE_UNAVAILABLE RejectCode = 1
)

// Enum value maps for RejectCode.
var (
	RejectCode_name = map[int32]string{
		0: "REJECT_CODE_UNSPECIFIED",
		1: "REJECT_CODE_PRICE_ORACLE_UNAVAILABLE",
	}
	RejectCode_value = map[string]int32{
		"REJECT_CODE_UNSPECIFIED":              0,
		"REJECT_CODE_PRICE_ORACLE_UNAVAILABLE": 1,
	}
)

func (x RejectCode) Enum() *RejectCode {
	p := new(RejectCode)
	*p = x
	return p
}

func (x RejectCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectCode) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[2].Descriptor()
}

func (RejectCode) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[2]
}

func (x RejectCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectCode.Descriptor instead.
func (RejectCode) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{2}
}

// QuoteRespStatus is an enum that represents the status of a quote response.
type QuoteRespStatus int32

const (
	// INVALID_ASSET_RATES indicates that at least one asset rate in the
	// quote response is invalid.
	QuoteRespStatus_INVALID_ASSET_RATES QuoteRespStatus = 0
	// INVALID_EXPIRY indicates that the expiry in the quote response is
	// invalid.
	QuoteRespStatus_INVALID_EXPIRY QuoteRespStatus = 1
	// PRICE_ORACLE_QUERY_ERR indicates that an error occurred when querying the
	// price oracle whilst evaluating the quote response.
	QuoteRespStatus_PRICE_ORACLE_QUERY_ERR QuoteRespStatus = 2
	// PORTFOLIO_PILOT_ERR indicates that an unexpected error occurred in the
	// portfolio pilot while evaluating the quote response.
	QuoteRespStatus_PORTFOLIO_PILOT_ERR QuoteRespStatus = 3
	// VALID_ACCEPT_QUOTE indicates that the accepted quote passed all
	// validation checks successfully.
	QuoteRespStatus_VALID_ACCEPT_QUOTE QuoteRespStatus = 4
)

// Enum value maps for QuoteRespStatus.
var (
	QuoteRespStatus_name = map[int32]string{
		0: "INVALID_ASSET_RATES",
		1: "INVALID_EXPIRY",
		2: "PRICE_ORACLE_QUERY_ERR",
		3: "PORTFOLIO_PILOT_ERR",
		4: "VALID_ACCEPT_QUOTE",
	}
	QuoteRespStatus_value = map[string]int32{
		"INVALID_ASSET_RATES":    0,
		"INVALID_EXPIRY":         1,
		"PRICE_ORACLE_QUERY_ERR": 2,
		"PORTFOLIO_PILOT_ERR":    3,
		"VALID_ACCEPT_QUOTE":     4,
	}
)

func (x QuoteRespStatus) Enum() *QuoteRespStatus {
	p := new(QuoteRespStatus)
	*p = x
	return p
}

func (x QuoteRespStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuoteRespStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[3].Descriptor()
}

func (QuoteRespStatus) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[3]
}

func (x QuoteRespStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuoteRespStatus.Descriptor instead.
func (QuoteRespStatus) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{3}
}

// RejectErr captures a rejection reason for a quote request.
type RejectErr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// code is the error code.
	Code RejectCode `protobuf:"varint,1,opt,name=code,proto3,enum=portfoliopilotrpc.RejectCode" json:"code,omitempty"`
	// message is a human-readable error message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RejectErr) Reset() {
	*x = RejectErr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectErr) ProtoMessage() {}

func (x *RejectErr) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectErr.ProtoReflect.Descriptor instead.
func (*RejectErr) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{0}
}

func (x *RejectErr) GetCode() RejectCode {
	if x != nil {
		return x.Code
	}
	return RejectCode_REJECT_CODE_UNSPECIFIED
}

func (x *RejectErr) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AssetSpecifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//
	//	*AssetSpecifier_AssetId
	//	*AssetSpecifier_AssetIdStr
	//	*AssetSpecifier_GroupKey
	//	*AssetSpecifier_GroupKeyStr
	Id isAssetSpecifier_Id `protobuf_oneof:"id"`
}

func (x *AssetSpecifier) Reset() {
	*x = AssetSpecifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetSpecifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSpecifier) ProtoMessage() {}

func (x *AssetSpecifier) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSpecifier.ProtoReflect.Descriptor instead.
func (*AssetSpecifier) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{1}
}

func (m *AssetSpecifier) GetId() isAssetSpecifier_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *AssetSpecifier) GetAssetId() []byte {
	if x, ok := x.GetId().(*AssetSpecifier_AssetId); ok {
		return x.AssetId
	}
	return nil
}

func (x *AssetSpecifier) GetAssetIdStr() string {
	if x, ok := x.GetId().(*AssetSpecifier_AssetIdStr); ok {
		return x.AssetIdStr
	}
	return ""
}

func (x *AssetSpecifier) GetGroupKey() []byte {
	if x, ok := x.GetId().(*AssetSpecifier_GroupKey); ok {
		return x.GroupKey
	}
	return nil
}

func (x *AssetSpecifier) GetGroupKeyStr() string {
	if x, ok := x.GetId().(*AssetSpecifier_GroupKeyStr); ok {
		return x.GroupKeyStr
	}
	return ""
}

type isAssetSpecifier_Id interface {
	isAssetSpecifier_Id()
}

type AssetSpecifier_AssetId struct {
	// The 32-byte asset ID specified as raw bytes (gRPC only).
	AssetId []byte `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3,oneof"`
}

type AssetSpecifier_AssetIdStr struct {
	// The 32-byte asset ID encoded as a hex string (use this for REST).
	AssetIdStr string `protobuf:"bytes,2,opt,name=asset_id_str,json=assetIdStr,proto3,oneof"`
}

type AssetSpecifier_GroupKey struct {
	// The 32-byte asset group key specified as raw bytes (gRPC only).
	GroupKey []byte `protobuf:"bytes,3,opt,name=group_key,json=groupKey,proto3,oneof"`
}

type AssetSpecifier_GroupKeyStr struct {
	// The 32-byte asset group key encoded as hex string (use this for
	// REST).
	GroupKeyStr string `protobuf:"bytes,4,opt,name=group_key_str,json=groupKeyStr,proto3,oneof"`
}

func (*AssetSpecifier_AssetId) isAssetSpecifier_Id() {}

func (*AssetSpecifier_AssetIdStr) isAssetSpecifier_Id() {}

func (*AssetSpecifier_GroupKey) isAssetSpecifier_Id() {}

func (*AssetSpecifier_GroupKeyStr) isAssetSpecifier_Id() {}

// FixedPoint is a scaled integer representation of a fractional number.
//
// This type consists of two integer fields: a coefficient and a scale.
// Using this format enables precise and consistent representation of fractional
// numbers while avoiding floating-point data types, which are prone to
// precision errors.
//
// The relationship between the fractional representation and its fixed-point
// representation is expressed as:
// ```
// V = F_c / (10^F_s)
// ```
// where:
//
// * `V` is the fractional value.
//
//   - `F_c` is the coefficient component of the fixed-point representation. It is
//     the scaled-up fractional value represented as an integer.
//
//   - `F_s` is the scale component. It is an integer specifying how
//     many decimal places `F_c` should be divided by to obtain the fractional
//     representation.
type FixedPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The coefficient is the fractional value scaled-up as an integer. This
	// integer is represented as a string as it may be too large to fit in a
	// uint64.
	Coefficient string `protobuf:"bytes,1,opt,name=coefficient,proto3" json:"coefficient,omitempty"`
	// The scale is the component that determines how many decimal places
	// the coefficient should be divided by to obtain the fractional value.
	Scale uint32 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *FixedPoint) Reset() {
	*x = FixedPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FixedPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedPoint) ProtoMessage() {}

func (x *FixedPoint) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedPoint.ProtoReflect.Descriptor instead.
func (*FixedPoint) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{2}
}

func (x *FixedPoint) GetCoefficient() string {
	if x != nil {
		return x.Coefficient
	}
	return ""
}

func (x *FixedPoint) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// AssetRate represents the exchange rate of an asset to BTC along with an
// expiry timestamp in seconds.
type AssetRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// rate is the asset to BTC conversion rate represented as a fixed-point
	// number.
	Rate *FixedPoint `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	// expiry_timestamp is the Unix timestamp in seconds after which the rate
	// is no longer valid.
	ExpiryTimestamp uint64 `protobuf:"varint,2,opt,name=expiry_timestamp,json=expiryTimestamp,proto3" json:"expiry_timestamp,omitempty"`
}

func (x *AssetRate) Reset() {
	*x = AssetRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRate) ProtoMessage() {}

func (x *AssetRate) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetRate.ProtoReflect.Descriptor instead.
func (*AssetRate) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{3}
}

func (x *AssetRate) GetRate() *FixedPoint {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *AssetRate) GetExpiryTimestamp() uint64 {
	if x != nil {
		return x.ExpiryTimestamp
	}
	return 0
}

// BuyRequest represents a request to buy the subject asset.
type BuyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// asset_specifier is the subject asset.
	AssetSpecifier *AssetSpecifier `protobuf:"bytes,1,opt,name=asset_specifier,json=assetSpecifier,proto3" json:"asset_specifier,omitempty"`
	// asset_max_amount is the maximum amount of the asset that the peer must
	// be willing to offer.
	AssetMaxAmount uint64 `protobuf:"varint,2,opt,name=asset_max_amount,json=assetMaxAmount,proto3" json:"asset_max_amount,omitempty"`
	// asset_rate_hint is an optional suggested asset rate for the request.
	AssetRateHint *AssetRate `protobuf:"bytes,3,opt,name=asset_rate_hint,json=assetRateHint,proto3" json:"asset_rate_hint,omitempty"`
	// price_oracle_metadata is optional metadata for pricing decisions.
	PriceOracleMetadata string `protobuf:"bytes,4,opt,name=price_oracle_metadata,json=priceOracleMetadata,proto3" json:"price_oracle_metadata,omitempty"`
	// peer_id is the 33-byte public key of the counterparty peer.
	PeerId []byte `protobuf:"bytes,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{4}
}

func (x *BuyRequest) GetAssetSpecifier() *AssetSpecifier {
	if x != nil {
		return x.AssetSpecifier
	}
	return nil
}

func (x *BuyRequest) GetAssetMaxAmount() uint64 {
	if x != nil {
		return x.AssetMaxAmount
	}
	return 0
}

func (x *BuyRequest) GetAssetRateHint() *AssetRate {
	if x != nil {
		return x.AssetRateHint
	}
	return nil
}

func (x *BuyRequest) GetPriceOracleMetadata() string {
	if x != nil {
		return x.PriceOracleMetadata
	}
	return ""
}

func (x *BuyRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

// SellRequest represents a request to sell the subject asset.
type SellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// asset_specifier is the subject asset.
	AssetSpecifier *AssetSpecifier `protobuf:"bytes,1,opt,name=asset_specifier,json=assetSpecifier,proto3" json:"asset_specifier,omitempty"`
	// payment_max_amount is the maximum msat amount that the peer must agree
	// to pay.
	PaymentMaxAmount uint64 `protobuf:"varint,2,opt,name=payment_max_amount,json=paymentMaxAmount,proto3" json:"payment_max_amount,omitempty"`
	// asset_rate_hint is an optional suggested asset rate for the request.
	AssetRateHint *AssetRate `protobuf:"bytes,3,opt,name=asset_rate_hint,json=assetRateHint,proto3" json:"asset_rate_hint,omitempty"`
	// price_oracle_metadata is optional metadata for pricing decisions.
	PriceOracleMetadata string `protobuf:"bytes,4,opt,name=price_oracle_metadata,json=priceOracleMetadata,proto3" json:"price_oracle_metadata,omitempty"`
	// peer_id is the 33-byte public key of the counterparty peer.
	PeerId []byte `protobuf:"bytes,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{5}
}

func (x *SellRequest) GetAssetSpecifier() *AssetSpecifier {
	if x != nil {
		return x.AssetSpecifier
	}
	return nil
}

func (x *SellRequest) GetPaymentMaxAmount() uint64 {
	if x != nil {
		return x.PaymentMaxAmount
	}
	return 0
}

func (x *SellRequest) GetAssetRateHint() *AssetRate {
	if x != nil {
		return x.AssetRateHint
	}
	return nil
}

func (x *SellRequest) GetPriceOracleMetadata() string {
	if x != nil {
		return x.PriceOracleMetadata
	}
	return ""
}

func (x *SellRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

// ResolveRequestRequest specifies a quote request to resolve.
type ResolveRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*ResolveRequestRequest_BuyRequest
	//	*ResolveRequestRequest_SellRequest
	Request isResolveRequestRequest_Request `protobuf_oneof:"request"`
}

func (x *ResolveRequestRequest) Reset() {
	*x = ResolveRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequestRequest) ProtoMessage() {}

func (x *ResolveRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequestRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequestRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{6}
}

func (m *ResolveRequestRequest) GetRequest() isResolveRequestRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ResolveRequestRequest) GetBuyRequest() *BuyRequest {
	if x, ok := x.GetRequest().(*ResolveRequestRequest_BuyRequest); ok {
		return x.BuyRequest
	}
	return nil
}

func (x *ResolveRequestRequest) GetSellRequest() *SellRequest {
	if x, ok := x.GetRequest().(*ResolveRequestRequest_SellRequest); ok {
		return x.SellRequest
	}
	return nil
}

type isResolveRequestRequest_Request interface {
	isResolveRequestRequest_Request()
}

type ResolveRequestRequest_BuyRequest struct {
	// buy_request is a request to buy the subject asset.
	BuyRequest *BuyRequest `protobuf:"bytes,1,opt,name=buy_request,json=buyRequest,proto3,oneof"`
}

type ResolveRequestRequest_SellRequest struct {
	// sell_request is a request to sell the subject asset.
	SellRequest *SellRequest `protobuf:"bytes,2,opt,name=sell_request,json=sellRequest,proto3,oneof"`
}

func (*ResolveRequestRequest_BuyRequest) isResolveRequestRequest_Request() {}

func (*ResolveRequestRequest_SellRequest) isResolveRequestRequest_Request() {}

// ResolveRequestResponse is the response to a ResolveRequest call.
type ResolveRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*ResolveRequestResponse_Accept
	//	*ResolveRequestResponse_Reject
	Result isResolveRequestResponse_Result `protobuf_oneof:"result"`
}

func (x *ResolveRequestResponse) Reset() {
	*x = ResolveRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequestResponse) ProtoMessage() {}

func (x *ResolveRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequestResponse.ProtoReflect.Descriptor instead.
func (*ResolveRequestResponse) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{7}
}

func (m *ResolveRequestResponse) GetResult() isResolveRequestResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ResolveRequestResponse) GetAccept() *AssetRate {
	if x, ok := x.GetResult().(*ResolveRequestResponse_Accept); ok {
		return x.Accept
	}
	return nil
}

func (x *ResolveRequestResponse) GetReject() *RejectErr {
	if x, ok := x.GetResult().(*ResolveRequestResponse_Reject); ok {
		return x.Reject
	}
	return nil
}

type isResolveRequestResponse_Result interface {
	isResolveRequestResponse_Result()
}

type ResolveRequestResponse_Accept struct {
	// accept is the accepted asset rate for the request.
	Accept *AssetRate `protobuf:"bytes,1,opt,name=accept,proto3,oneof"`
}

type ResolveRequestResponse_Reject struct {
	// reject is the rejection reason for the request.
	Reject *RejectErr `protobuf:"bytes,2,opt,name=reject,proto3,oneof"`
}

func (*ResolveRequestResponse_Accept) isResolveRequestResponse_Result() {}

func (*ResolveRequestResponse_Reject) isResolveRequestResponse_Result() {}

// AcceptedQuote bundles an accepted quote and its original request.
type AcceptedQuote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// peer_id is the 33-byte public key of the accepting peer.
	PeerId []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// accepted_rate is the asset rate accepted by the peer.
	AcceptedRate *AssetRate `protobuf:"bytes,2,opt,name=accepted_rate,json=acceptedRate,proto3" json:"accepted_rate,omitempty"`
	// Types that are assignable to Request:
	//
	//	*AcceptedQuote_BuyRequest
	//	*AcceptedQuote_SellRequest
	Request isAcceptedQuote_Request `protobuf_oneof:"request"`
}

func (x *AcceptedQuote) Reset() {
	*x = AcceptedQuote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptedQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedQuote) ProtoMessage() {}

func (x *AcceptedQuote) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedQuote.ProtoReflect.Descriptor instead.
func (*AcceptedQuote) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptedQuote) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *AcceptedQuote) GetAcceptedRate() *AssetRate {
	if x != nil {
		return x.AcceptedRate
	}
	return nil
}

func (m *AcceptedQuote) GetRequest() isAcceptedQuote_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *AcceptedQuote) GetBuyRequest() *BuyRequest {
	if x, ok := x.GetRequest().(*AcceptedQuote_BuyRequest); ok {
		return x.BuyRequest
	}
	return nil
}

func (x *AcceptedQuote) GetSellRequest() *SellRequest {
	if x, ok := x.GetRequest().(*AcceptedQuote_SellRequest); ok {
		return x.SellRequest
	}
	return nil
}

type isAcceptedQuote_Request interface {
	isAcceptedQuote_Request()
}

type AcceptedQuote_BuyRequest struct {
	// buy_request is the original buy request.
	BuyRequest *BuyRequest `protobuf:"bytes,3,opt,name=buy_request,json=buyRequest,proto3,oneof"`
}

type AcceptedQuote_SellRequest struct {
	// sell_request is the original sell request.
	SellRequest *SellRequest `protobuf:"bytes,4,opt,name=sell_request,json=sellRequest,proto3,oneof"`
}

func (*AcceptedQuote_BuyRequest) isAcceptedQuote_Request() {}

func (*AcceptedQuote_SellRequest) isAcceptedQuote_Request() {}

// VerifyAcceptQuoteRequest specifies an accepted quote to verify.
type VerifyAcceptQuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// accept is the accepted quote and request details.
	Accept *AcceptedQuote `protobuf:"bytes,1,opt,name=accept,proto3" json:"accept,omitempty"`
}

func (x *VerifyAcceptQuoteRequest) Reset() {
	*x = VerifyAcceptQuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAcceptQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAcceptQuoteRequest) ProtoMessage() {}

func (x *VerifyAcceptQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAcceptQuoteRequest.ProtoReflect.Descriptor instead.
func (*VerifyAcceptQuoteRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyAcceptQuoteRequest) GetAccept() *AcceptedQuote {
	if x != nil {
		return x.Accept
	}
	return nil
}

// VerifyAcceptQuoteResponse is the response to a VerifyAcceptQuote call.
type VerifyAcceptQuoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status is the verification result.
	Status QuoteRespStatus `protobuf:"varint,1,opt,name=status,proto3,enum=portfoliopilotrpc.QuoteRespStatus" json:"status,omitempty"`
}

func (x *VerifyAcceptQuoteResponse) Reset() {
	*x = VerifyAcceptQuoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAcceptQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAcceptQuoteResponse) ProtoMessage() {}

func (x *VerifyAcceptQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAcceptQuoteResponse.ProtoReflect.Descriptor instead.
func (*VerifyAcceptQuoteResponse) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyAcceptQuoteResponse) GetStatus() QuoteRespStatus {
	if x != nil {
		return x.Status
	}
	return QuoteRespStatus_INVALID_ASSET_RATES
}

// QueryAssetRatesRequest specifies the parameters for querying asset rates.
type QueryAssetRatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// asset_specifier identifies the subject asset.
	AssetSpecifier *AssetSpecifier `protobuf:"bytes,1,opt,name=asset_specifier,json=assetSpecifier,proto3" json:"asset_specifier,omitempty"`
	// direction specifies whether we want to buy or sell the asset.
	Direction AssetTransferDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=portfoliopilotrpc.AssetTransferDirection" json:"direction,omitempty"`
	// intent specifies the purpose of the query.
	Intent Intent `protobuf:"varint,3,opt,name=intent,proto3,enum=portfoliopilotrpc.Intent" json:"intent,omitempty"`
	// asset_amount is an optional constraint on the asset amount. If set to
	// zero, it is considered unset.
	AssetAmount uint64 `protobuf:"varint,4,opt,name=asset_amount,json=assetAmount,proto3" json:"asset_amount,omitempty"`
	// payment_amount is an optional constraint on the payment amount in msat.
	// If set to zero, it is considered unset.
	PaymentAmount uint64 `protobuf:"varint,5,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	// asset_rate_hint is an optional suggested asset rate.
	AssetRateHint *AssetRate `protobuf:"bytes,6,opt,name=asset_rate_hint,json=assetRateHint,proto3" json:"asset_rate_hint,omitempty"`
	// price_oracle_metadata is optional metadata for pricing decisions.
	PriceOracleMetadata string `protobuf:"bytes,7,opt,name=price_oracle_metadata,json=priceOracleMetadata,proto3" json:"price_oracle_metadata,omitempty"`
	// peer_id is the 33-byte public key of the counterparty peer.
	PeerId []byte `protobuf:"bytes,8,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// expiry_timestamp is an optional expiry Unix timestamp (seconds) for the
	// query context. If set to zero, it is considered unset.
	ExpiryTimestamp uint64 `protobuf:"varint,9,opt,name=expiry_timestamp,json=expiryTimestamp,proto3" json:"expiry_timestamp,omitempty"`
}

func (x *QueryAssetRatesRequest) Reset() {
	*x = QueryAssetRatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAssetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAssetRatesRequest) ProtoMessage() {}

func (x *QueryAssetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAssetRatesRequest.ProtoReflect.Descriptor instead.
func (*QueryAssetRatesRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{11}
}

func (x *QueryAssetRatesRequest) GetAssetSpecifier() *AssetSpecifier {
	if x != nil {
		return x.AssetSpecifier
	}
	return nil
}

func (x *QueryAssetRatesRequest) GetDirection() AssetTransferDirection {
	if x != nil {
		return x.Direction
	}
	return AssetTransferDirection_ASSET_TRANSFER_DIRECTION_UNSPECIFIED
}

func (x *QueryAssetRatesRequest) GetIntent() Intent {
	if x != nil {
		return x.Intent
	}
	return Intent_INTENT_UNSPECIFIED
}

func (x *QueryAssetRatesRequest) GetAssetAmount() uint64 {
	if x != nil {
		return x.AssetAmount
	}
	return 0
}

func (x *QueryAssetRatesRequest) GetPaymentAmount() uint64 {
	if x != nil {
		return x.PaymentAmount
	}
	return 0
}

func (x *QueryAssetRatesRequest) GetAssetRateHint() *AssetRate {
	if x != nil {
		return x.AssetRateHint
	}
	return nil
}

func (x *QueryAssetRatesRequest) GetPriceOracleMetadata() string {
	if x != nil {
		return x.PriceOracleMetadata
	}
	return ""
}

func (x *QueryAssetRatesRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *QueryAssetRatesRequest) GetExpiryTimestamp() uint64 {
	if x != nil {
		return x.ExpiryTimestamp
	}
	return 0
}

// QueryAssetRatesResponse is the response to a QueryAssetRates call.
type QueryAssetRatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// asset_rate is the asset exchange rate response.
	AssetRate *AssetRate `protobuf:"bytes,1,opt,name=asset_rate,json=assetRate,proto3" json:"asset_rate,omitempty"`
}

func (x *QueryAssetRatesResponse) Reset() {
	*x = QueryAssetRatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAssetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAssetRatesResponse) ProtoMessage() {}

func (x *QueryAssetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAssetRatesResponse.ProtoReflect.Descriptor instead.
func (*QueryAssetRatesResponse) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{12}
}

func (x *QueryAssetRatesResponse) GetAssetRate() *AssetRate {
	if x != nil {
		return x.AssetRate
	}
	return nil
}

var File_portfoliopilotrpc_portfolio_pilot_proto protoreflect.FileDescriptor

var file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x5f, 0x70, 0x69,
	0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x70, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x22, 0x58, 0x0a, 0x09,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x72, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f,
	0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x08, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x53, 0x74, 0x72, 0x12, 0x1d, 0x0a, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x72, 0x42,
	0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x0a, 0x46, 0x69, 0x78, 0x65, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x69,
	0x63, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x69, 0x0a, 0x09, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c,
	0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x78, 0x65, 0x64,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x95, 0x02, 0x0a, 0x0a, 0x42, 0x75, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72,
	0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x0e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x4d, 0x61, 0x78, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x0f, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f,
	0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61,
	0x74, 0x65, 0x52, 0x0d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x69, 0x6e,
	0x74, 0x12, 0x32, 0x0a, 0x15, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c,
	0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x13, 0x70, 0x72, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0x9a,
	0x02, 0x0a, 0x0b, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a,
	0x0a, 0x0f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f,
	0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d,
	0x61, 0x78, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c,
	0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x0d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x32,
	0x0a, 0x15, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa9, 0x01, 0x0a, 0x15,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0b, 0x62, 0x75, 0x79, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x72,
	0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x42,
	0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x75, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0c, 0x73, 0x65, 0x6c, 0x6c, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70,
	0x63, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0b, 0x73, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69,
	0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x72, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x72,
	0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x72, 0x72, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xfd, 0x01, 0x0a,
	0x0d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72,
	0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x52, 0x61, 0x74, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x62, 0x75,
	0x79, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74,
	0x72, 0x70, 0x63, 0x2e, 0x42, 0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0a, 0x62, 0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0c,
	0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69,
	0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x18,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x22, 0x57, 0x0a, 0x19, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x22, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74,
	0x72, 0x70, 0x63, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xe8, 0x03, 0x0a, 0x16,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74,
	0x72, 0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x0e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x47, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69,
	0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x06, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x6f,
	0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c,
	0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x0d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x32,
	0x0a, 0x15, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x56, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69,
	0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x2a, 0x87,
	0x01, 0x0a, 0x16, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x24, 0x41, 0x53, 0x53,
	0x45, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x44, 0x49, 0x52, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x54, 0x52, 0x41,
	0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x42, 0x55, 0x59, 0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x54,
	0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02, 0x2a, 0xcd, 0x01, 0x0a, 0x06, 0x49, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x49,
	0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x41, 0x59, 0x5f, 0x49, 0x4e, 0x56, 0x4f, 0x49, 0x43,
	0x45, 0x5f, 0x48, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x54, 0x45,
	0x4e, 0x54, 0x5f, 0x50, 0x41, 0x59, 0x5f, 0x49, 0x4e, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x02,
	0x12, 0x1e, 0x0a, 0x1a, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x41, 0x59, 0x5f, 0x49,
	0x4e, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x5f, 0x51, 0x55, 0x41, 0x4c, 0x49, 0x46, 0x59, 0x10, 0x03,
	0x12, 0x1c, 0x0a, 0x18, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x56, 0x5f,
	0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x48, 0x49, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x17,
	0x0a, 0x13, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x56, 0x5f, 0x50, 0x41,
	0x59, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x05, 0x12, 0x1f, 0x0a, 0x1b, 0x49, 0x4e, 0x54, 0x45, 0x4e,
	0x54, 0x5f, 0x52, 0x45, 0x43, 0x56, 0x5f, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x51,
	0x55, 0x41, 0x4c, 0x49, 0x46, 0x59, 0x10, 0x06, 0x2a, 0x53, 0x0a, 0x0a, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54,
	0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x28, 0x0a, 0x24, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x50, 0x52, 0x49, 0x43, 0x45, 0x5f, 0x4f, 0x52, 0x41, 0x43, 0x4c, 0x45, 0x5f,
	0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x2a, 0x8b, 0x01,
	0x0a, 0x0f, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x53, 0x53,
	0x45, 0x54, 0x5f, 0x52, 0x41, 0x54, 0x45, 0x53, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x59, 0x10, 0x01, 0x12, 0x1a,
	0x0a, 0x16, 0x50, 0x52, 0x49, 0x43, 0x45, 0x5f, 0x4f, 0x52, 0x41, 0x43, 0x4c, 0x45, 0x5f, 0x51,
	0x55, 0x45, 0x52, 0x59, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x4f,
	0x52, 0x54, 0x46, 0x4f, 0x4c, 0x49, 0x4f, 0x5f, 0x50, 0x49, 0x4c, 0x4f, 0x54, 0x5f, 0x45, 0x52,
	0x52, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x43, 0x43,
	0x45, 0x50, 0x54, 0x5f, 0x51, 0x55, 0x4f, 0x54, 0x45, 0x10, 0x04, 0x32, 0xd1, 0x02, 0x0a, 0x0e,
	0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x50, 0x69, 0x6c, 0x6f, 0x74, 0x12, 0x65,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f,
	0x74, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x6f, 0x72,
	0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x70, 0x6f, 0x72,
	0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f,
	0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x12, 0x29, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70,
	0x69, 0x6c, 0x6f, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x6e, 0x69, 0x6e, 0x67, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x74, 0x61, 0x70, 0x72,
	0x6f, 0x6f, 0x74, 0x2d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x74, 0x61, 0x70, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x70, 0x69, 0x6c, 0x6f, 0x74,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_portfoliopilotrpc_portfolio_pilot_proto_rawDescOnce sync.Once
	file_portfoliopilotrpc_portfolio_pilot_proto_rawDescData = file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc
)

func file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP() []byte {
	file_portfoliopilotrpc_portfolio_pilot_proto_rawDescOnce.Do(func() {
		file_portfoliopilotrpc_portfolio_pilot_proto_rawDescData = protoimpl.X.CompressGZIP(file_portfoliopilotrpc_portfolio_pilot_proto_rawDescData)
	})
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescData
}

var file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_portfoliopilotrpc_portfolio_pilot_proto_goTypes = []any{
	(AssetTransferDirection)(0),       // 0: portfoliopilotrpc.AssetTransferDirection
	(Intent)(0),                       // 1: portfoliopilotrpc.Intent
	(RejectCode)(0),                   // 2: portfoliopilotrpc.RejectCode
	(QuoteRespStatus)(0),              // 3: portfoliopilotrpc.QuoteRespStatus
	(*RejectErr)(nil),                 // 4: portfoliopilotrpc.RejectErr
	(*AssetSpecifier)(nil),            // 5: portfoliopilotrpc.AssetSpecifier
	(*FixedPoint)(nil),                // 6: portfoliopilotrpc.FixedPoint
	(*AssetRate)(nil),                 // 7: portfoliopilotrpc.AssetRate
	(*BuyRequest)(nil),                // 8: portfoliopilotrpc.BuyRequest
	(*SellRequest)(nil),               // 9: portfoliopilotrpc.SellRequest
	(*ResolveRequestRequest)(nil),     // 10: portfoliopilotrpc.ResolveRequestRequest
	(*ResolveRequestResponse)(nil),    // 11: portfoliopilotrpc.ResolveRequestResponse
	(*AcceptedQuote)(nil),             // 12: portfoliopilotrpc.AcceptedQuote
	(*VerifyAcceptQuoteRequest)(nil),  // 13: portfoliopilotrpc.VerifyAcceptQuoteRequest
	(*VerifyAcceptQuoteResponse)(nil), // 14: portfoliopilotrpc.VerifyAcceptQuoteResponse
	(*QueryAssetRatesRequest)(nil),    // 15: portfoliopilotrpc.QueryAssetRatesRequest
	(*QueryAssetRatesResponse)(nil),   // 16: portfoliopilotrpc.QueryAssetRatesResponse
}
var file_portfoliopilotrpc_portfolio_pilot_proto_depIdxs = []int32{
	2,  // 0: portfoliopilotrpc.RejectErr.code:type_name -> portfoliopilotrpc.RejectCode
	6,  // 1: portfoliopilotrpc.AssetRate.rate:type_name -> portfoliopilotrpc.FixedPoint
	5,  // 2: portfoliopilotrpc.BuyRequest.asset_specifier:type_name -> portfoliopilotrpc.AssetSpecifier
	7,  // 3: portfoliopilotrpc.BuyRequest.asset_rate_hint:type_name -> portfoliopilotrpc.AssetRate
	5,  // 4: portfoliopilotrpc.SellRequest.asset_specifier:type_name -> portfoliopilotrpc.AssetSpecifier
	7,  // 5: portfoliopilotrpc.SellRequest.asset_rate_hint:type_name -> portfoliopilotrpc.AssetRate
	8,  // 6: portfoliopilotrpc.ResolveRequestRequest.buy_request:type_name -> portfoliopilotrpc.BuyRequest
	9,  // 7: portfoliopilotrpc.ResolveRequestRequest.sell_request:type_name -> portfoliopilotrpc.SellRequest
	7,  // 8: portfoliopilotrpc.ResolveRequestResponse.accept:type_name -> portfoliopilotrpc.AssetRate
	4,  // 9: portfoliopilotrpc.ResolveRequestResponse.reject:type_name -> portfoliopilotrpc.RejectErr
	7,  // 10: portfoliopilotrpc.AcceptedQuote.accepted_rate:type_name -> portfoliopilotrpc.AssetRate
	8,  // 11: portfoliopilotrpc.AcceptedQuote.buy_request:type_name -> portfoliopilotrpc.BuyRequest
	9,  // 12: portfoliopilotrpc.AcceptedQuote.sell_request:type_name -> portfoliopilotrpc.SellRequest
	12, // 13: portfoliopilotrpc.VerifyAcceptQuoteRequest.accept:type_name -> portfoliopilotrpc.AcceptedQuote
	3,  // 14: portfoliopilotrpc.VerifyAcceptQuoteResponse.status:type_name -> portfoliopilotrpc.QuoteRespStatus
	5,  // 15: portfoliopilotrpc.QueryAssetRatesRequest.asset_specifier:type_name -> portfoliopilotrpc.AssetSpecifier
	0,  // 16: portfoliopilotrpc.QueryAssetRatesRequest.direction:type_name -> portfoliopilotrpc.AssetTransferDirection
	1,  // 17: portfoliopilotrpc.QueryAssetRatesRequest.intent:type_name -> portfoliopilotrpc.Intent
	7,  // 18: portfoliopilotrpc.QueryAssetRatesRequest.asset_rate_hint:type_name -> portfoliopilotrpc.AssetRate
	7,  // 19: portfoliopilotrpc.QueryAssetRatesResponse.asset_rate:type_name -> portfoliopilotrpc.AssetRate
	10, // 20: portfoliopilotrpc.PortfolioPilot.ResolveRequest:input_type -> portfoliopilotrpc.ResolveRequestRequest
	13, // 21: portfoliopilotrpc.PortfolioPilot.VerifyAcceptQuote:input_type -> portfoliopilotrpc.VerifyAcceptQuoteRequest
	15, // 22: portfoliopilotrpc.PortfolioPilot.QueryAssetRates:input_type -> portfoliopilotrpc.QueryAssetRatesRequest
	11, // 23: portfoliopilotrpc.PortfolioPilot.ResolveRequest:output_type -> portfoliopilotrpc.ResolveRequestResponse
	14, // 24: portfoliopilotrpc.PortfolioPilot.VerifyAcceptQuote:output_type -> portfoliopilotrpc.VerifyAcceptQuoteResponse
	16, // 25: portfoliopilotrpc.PortfolioPilot.QueryAssetRates:output_type -> portfoliopilotrpc.QueryAssetRatesResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_portfoliopilotrpc_portfolio_pilot_proto_init() }
func file_portfoliopilotrpc_portfolio_pilot_proto_init() {
	if File_portfoliopilotrpc_portfolio_pilot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RejectErr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AssetSpecifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FixedPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AssetRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BuyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ResolveRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ResolveRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AcceptedQuote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyAcceptQuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyAcceptQuoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*QueryAssetRatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*QueryAssetRatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[1].OneofWrappers = []any{
		(*AssetSpecifier_AssetId)(nil),
		(*AssetSpecifier_AssetIdStr)(nil),
		(*AssetSpecifier_GroupKey)(nil),
		(*AssetSpecifier_GroupKeyStr)(nil),
	}
	file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[6].OneofWrappers = []any{
		(*ResolveRequestRequest_BuyRequest)(nil),
		(*ResolveRequestRequest_SellRequest)(nil),
	}
	file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[7].OneofWrappers = []any{
		(*ResolveRequestResponse_Accept)(nil),
		(*ResolveRequestResponse_Reject)(nil),
	}
	file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[8].OneofWrappers = []any{
		(*AcceptedQuote_BuyRequest)(nil),
		(*AcceptedQuote_SellRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfoliopilotrpc_portfolio_pilot_proto_goTypes,
		DependencyIndexes: file_portfoliopilotrpc_portfolio_pilot_proto_depIdxs,
		EnumInfos:         file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes,
		MessageInfos:      file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes,
	}.Build()
	File_portfoliopilotrpc_portfolio_pilot_proto = out.File
	file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc = nil
	file_portfoliopilotrpc_portfolio_pilot_proto_goTypes = nil
	file_portfoliopilotrpc_portfolio_pilot_proto_depIdxs = nil
}
