// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: portfoliopilotrpc/portfolio_pilot.proto

package portfoliopilotrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssetTransferDirection represents the direction of an asset transfer from
// our perspective for pricing and rate queries.
type AssetTransferDirection int32

const (
	// ASSET_TRANSFER_DIRECTION_UNSPECIFIED indicates an unspecified direction.
	AssetTransferDirection_ASSET_TRANSFER_DIRECTION_UNSPECIFIED AssetTransferDirection = 0
	// ASSET_TRANSFER_DIRECTION_BUY indicates we want to buy the asset.
	AssetTransferDirection_ASSET_TRANSFER_DIRECTION_BUY AssetTransferDirection = 1
	// ASSET_TRANSFER_DIRECTION_SELL indicates we want to sell the asset.
	AssetTransferDirection_ASSET_TRANSFER_DIRECTION_SELL AssetTransferDirection = 2
)

// Enum value maps for AssetTransferDirection.
var (
	AssetTransferDirection_name = map[int32]string{
		0: "ASSET_TRANSFER_DIRECTION_UNSPECIFIED",
		1: "ASSET_TRANSFER_DIRECTION_BUY",
		2: "ASSET_TRANSFER_DIRECTION_SELL",
	}
	AssetTransferDirection_value = map[string]int32{
		"ASSET_TRANSFER_DIRECTION_UNSPECIFIED": 0,
		"ASSET_TRANSFER_DIRECTION_BUY":         1,
		"ASSET_TRANSFER_DIRECTION_SELL":        2,
	}
)

func (x AssetTransferDirection) Enum() *AssetTransferDirection {
	p := new(AssetTransferDirection)
	*p = x
	return p
}

func (x AssetTransferDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetTransferDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[0].Descriptor()
}

func (AssetTransferDirection) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[0]
}

func (x AssetTransferDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetTransferDirection.Descriptor instead.
func (AssetTransferDirection) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{0}
}

// Intent is an enum informing the portfolio pilot about the intent of the
// price rate query. This is used to provide context for the asset rates being
// requested, allowing the pilot to tailor the response based on the specific
// use case, such as paying an invoice or receiving a payment and the different
// stages involved in those.
type Intent int32

const (
	// INTENT_UNSPECIFIED is used to indicate that the intent of the price rate
	// query is not specified. This is the fallback default value and should not
	// be used in production code. It is primarily used for backward
	// compatibility with older versions of the protocol that did not include
	// intent information.
	Intent_INTENT_UNSPECIFIED Intent = 0
	// INTENT_PAY_INVOICE_HINT is used to indicate that the user is requesting
	// a price rate hint for paying an invoice. This is typically used by the
	// payer of an invoice to provide a suggestion of the expected asset rate to
	// the RFQ peer (edge node) that will determine the actual rate for the
	// payment.
	Intent_INTENT_PAY_INVOICE_HINT Intent = 1
	// INTENT_PAY_INVOICE is used to indicate that a peer wants to pay an
	// invoice with assets. This is typically used by the edge node that
	// facilitates the swap from assets to BTC for the payer of an invoice. This
	// intent is used to provide the actual asset rate for the payment, which
	// may differ from the hint provided by the payer.
	Intent_INTENT_PAY_INVOICE Intent = 2
	// INTENT_PAY_INVOICE_QUALIFY is used to indicate that the payer of an
	// invoice has received an asset rate from their RFQ peer (edge node) and is
	// qualifying the rate for the payment. This is typically used by the payer
	// of an invoice to ensure that the asset rate provided by their peer (edge
	// node) is acceptable before proceeding with the payment.
	Intent_INTENT_PAY_INVOICE_QUALIFY Intent = 3
	// INTENT_RECV_PAYMENT_HINT is used to indicate that the user is requesting
	// a price rate hint for receiving a payment through an invoice. This is
	// typically used by the creator of an invoice to provide a suggestion of
	// the expected asset rate to the RFQ peer (edge node) that will determine
	// the actual rate used for creating an invoice.
	Intent_INTENT_RECV_PAYMENT_HINT Intent = 4
	// INTENT_RECV_PAYMENT is used to indicate that a peer wants to create an
	// invoice to receive a payment with assets. This is typically used by the
	// edge node that facilitates the swap from BTC to assets for the receiver
	// of a payment. This intent is used to provide the actual asset rate for
	// the invoice creation, which may differ from the hint provided by the
	// receiver.
	Intent_INTENT_RECV_PAYMENT Intent = 5
	// INTENT_RECV_PAYMENT_QUALIFY is used to indicate that the creator of an
	// invoice received an asset rate from their RFQ peer (edge node) and is
	// qualifying the rate for the creation of the invoice. This is typically
	// used by the creator of an invoice to ensure that the asset rate provided
	// by their peer (edge node) is acceptable before proceeding with creating
	// the invoice.
	Intent_INTENT_RECV_PAYMENT_QUALIFY Intent = 6
)

// Enum value maps for Intent.
var (
	Intent_name = map[int32]string{
		0: "INTENT_UNSPECIFIED",
		1: "INTENT_PAY_INVOICE_HINT",
		2: "INTENT_PAY_INVOICE",
		3: "INTENT_PAY_INVOICE_QUALIFY",
		4: "INTENT_RECV_PAYMENT_HINT",
		5: "INTENT_RECV_PAYMENT",
		6: "INTENT_RECV_PAYMENT_QUALIFY",
	}
	Intent_value = map[string]int32{
		"INTENT_UNSPECIFIED":          0,
		"INTENT_PAY_INVOICE_HINT":     1,
		"INTENT_PAY_INVOICE":          2,
		"INTENT_PAY_INVOICE_QUALIFY":  3,
		"INTENT_RECV_PAYMENT_HINT":    4,
		"INTENT_RECV_PAYMENT":         5,
		"INTENT_RECV_PAYMENT_QUALIFY": 6,
	}
)

func (x Intent) Enum() *Intent {
	p := new(Intent)
	*p = x
	return p
}

func (x Intent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Intent) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[1].Descriptor()
}

func (Intent) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[1]
}

func (x Intent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Intent.Descriptor instead.
func (Intent) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{1}
}

// ExecutionPolicy specifies how a quote request should be filled.
type ExecutionPolicy int32

const (
	// EXECUTION_POLICY_IOC (Immediate-Or-Cancel) accepts any partial
	// fill. This is the default policy.
	ExecutionPolicy_EXECUTION_POLICY_IOC ExecutionPolicy = 0
	// EXECUTION_POLICY_FOK (Fill-Or-Kill) requires the accepted rate
	// to satisfy the full requested amount.
	ExecutionPolicy_EXECUTION_POLICY_FOK ExecutionPolicy = 1
)

// Enum value maps for ExecutionPolicy.
var (
	ExecutionPolicy_name = map[int32]string{
		0: "EXECUTION_POLICY_IOC",
		1: "EXECUTION_POLICY_FOK",
	}
	ExecutionPolicy_value = map[string]int32{
		"EXECUTION_POLICY_IOC": 0,
		"EXECUTION_POLICY_FOK": 1,
	}
)

func (x ExecutionPolicy) Enum() *ExecutionPolicy {
	p := new(ExecutionPolicy)
	*p = x
	return p
}

func (x ExecutionPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[2].Descriptor()
}

func (ExecutionPolicy) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[2]
}

func (x ExecutionPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionPolicy.Descriptor instead.
func (ExecutionPolicy) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{2}
}

// RejectCode represents the possible error codes that can be returned in a
// ResolveRequestResponse reject result.
type RejectCode int32

const (
	// REJECT_CODE_UNSPECIFIED indicates an unspecified error.
	RejectCode_REJECT_CODE_UNSPECIFIED RejectCode = 0
	// REJECT_CODE_PRICE_ORACLE_UNAVAILABLE indicates that pricing could not be
	// provided due to an unavailable oracle.
	RejectCode_REJECT_CODE_PRICE_ORACLE_UNAVAILABLE RejectCode = 1
	// REJECT_CODE_MIN_FILL_NOT_MET indicates that the minimum fill
	// constraint was not satisfiable at the accepted rate.
	RejectCode_REJECT_CODE_MIN_FILL_NOT_MET RejectCode = 2
	// REJECT_CODE_PRICE_BOUND_MISS indicates that the accepted rate
	// violated the requester's rate limit constraint.
	RejectCode_REJECT_CODE_PRICE_BOUND_MISS RejectCode = 3
	// REJECT_CODE_FOK_NOT_VIABLE indicates that the FOK execution
	// policy could not be satisfied at the accepted rate.
	RejectCode_REJECT_CODE_FOK_NOT_VIABLE RejectCode = 4
	// REJECT_CODE_FILL_EXCEEDS_MAX indicates that the negotiated
	// fill amount exceeds the requester's maximum.
	RejectCode_REJECT_CODE_FILL_EXCEEDS_MAX RejectCode = 5
)

// Enum value maps for RejectCode.
var (
	RejectCode_name = map[int32]string{
		0: "REJECT_CODE_UNSPECIFIED",
		1: "REJECT_CODE_PRICE_ORACLE_UNAVAILABLE",
		2: "REJECT_CODE_MIN_FILL_NOT_MET",
		3: "REJECT_CODE_PRICE_BOUND_MISS",
		4: "REJECT_CODE_FOK_NOT_VIABLE",
		5: "REJECT_CODE_FILL_EXCEEDS_MAX",
	}
	RejectCode_value = map[string]int32{
		"REJECT_CODE_UNSPECIFIED":              0,
		"REJECT_CODE_PRICE_ORACLE_UNAVAILABLE": 1,
		"REJECT_CODE_MIN_FILL_NOT_MET":         2,
		"REJECT_CODE_PRICE_BOUND_MISS":         3,
		"REJECT_CODE_FOK_NOT_VIABLE":           4,
		"REJECT_CODE_FILL_EXCEEDS_MAX":         5,
	}
)

func (x RejectCode) Enum() *RejectCode {
	p := new(RejectCode)
	*p = x
	return p
}

func (x RejectCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectCode) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[3].Descriptor()
}

func (RejectCode) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[3]
}

func (x RejectCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectCode.Descriptor instead.
func (RejectCode) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{3}
}

// QuoteRespStatus is an enum that represents the status of a quote response.
type QuoteRespStatus int32

const (
	// INVALID_ASSET_RATES indicates that at least one asset rate in the
	// quote response is invalid.
	QuoteRespStatus_INVALID_ASSET_RATES QuoteRespStatus = 0
	// INVALID_EXPIRY indicates that the expiry in the quote response is
	// invalid.
	QuoteRespStatus_INVALID_EXPIRY QuoteRespStatus = 1
	// PRICE_ORACLE_QUERY_ERR indicates that an error occurred when querying the
	// price oracle whilst evaluating the quote response.
	QuoteRespStatus_PRICE_ORACLE_QUERY_ERR QuoteRespStatus = 2
	// PORTFOLIO_PILOT_ERR indicates that an unexpected error occurred in the
	// portfolio pilot while evaluating the quote response.
	QuoteRespStatus_PORTFOLIO_PILOT_ERR QuoteRespStatus = 3
	// VALID_ACCEPT_QUOTE indicates that the accepted quote passed all
	// validation checks successfully.
	QuoteRespStatus_VALID_ACCEPT_QUOTE QuoteRespStatus = 4
	// MIN_FILL_NOT_MET indicates that the minimum fill constraint was
	// not satisfiable at the accepted rate.
	QuoteRespStatus_MIN_FILL_NOT_MET QuoteRespStatus = 5
	// RATE_BOUND_MISS indicates that the accepted rate violated the
	// requester's rate limit constraint.
	QuoteRespStatus_RATE_BOUND_MISS QuoteRespStatus = 6
	// FOK_NOT_VIABLE indicates that the FOK execution policy could
	// not be satisfied at the accepted rate.
	QuoteRespStatus_FOK_NOT_VIABLE QuoteRespStatus = 7
	// FILL_EXCEEDS_MAX indicates that the negotiated fill amount
	// exceeds the requester's maximum.
	QuoteRespStatus_FILL_EXCEEDS_MAX QuoteRespStatus = 8
)

// Enum value maps for QuoteRespStatus.
var (
	QuoteRespStatus_name = map[int32]string{
		0: "INVALID_ASSET_RATES",
		1: "INVALID_EXPIRY",
		2: "PRICE_ORACLE_QUERY_ERR",
		3: "PORTFOLIO_PILOT_ERR",
		4: "VALID_ACCEPT_QUOTE",
		5: "MIN_FILL_NOT_MET",
		6: "RATE_BOUND_MISS",
		7: "FOK_NOT_VIABLE",
		8: "FILL_EXCEEDS_MAX",
	}
	QuoteRespStatus_value = map[string]int32{
		"INVALID_ASSET_RATES":    0,
		"INVALID_EXPIRY":         1,
		"PRICE_ORACLE_QUERY_ERR": 2,
		"PORTFOLIO_PILOT_ERR":    3,
		"VALID_ACCEPT_QUOTE":     4,
		"MIN_FILL_NOT_MET":       5,
		"RATE_BOUND_MISS":        6,
		"FOK_NOT_VIABLE":         7,
		"FILL_EXCEEDS_MAX":       8,
	}
)

func (x QuoteRespStatus) Enum() *QuoteRespStatus {
	p := new(QuoteRespStatus)
	*p = x
	return p
}

func (x QuoteRespStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuoteRespStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[4].Descriptor()
}

func (QuoteRespStatus) Type() protoreflect.EnumType {
	return &file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes[4]
}

func (x QuoteRespStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuoteRespStatus.Descriptor instead.
func (QuoteRespStatus) EnumDescriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{4}
}

// RejectErr captures a rejection reason for a quote request.
type RejectErr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the error code.
	Code RejectCode `protobuf:"varint,1,opt,name=code,proto3,enum=portfoliopilotrpc.RejectCode" json:"code,omitempty"`
	// message is a human-readable error message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectErr) Reset() {
	*x = RejectErr{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectErr) ProtoMessage() {}

func (x *RejectErr) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectErr.ProtoReflect.Descriptor instead.
func (*RejectErr) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{0}
}

func (x *RejectErr) GetCode() RejectCode {
	if x != nil {
		return x.Code
	}
	return RejectCode_REJECT_CODE_UNSPECIFIED
}

func (x *RejectErr) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AssetSpecifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*AssetSpecifier_AssetId
	//	*AssetSpecifier_AssetIdStr
	//	*AssetSpecifier_GroupKey
	//	*AssetSpecifier_GroupKeyStr
	Id            isAssetSpecifier_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetSpecifier) Reset() {
	*x = AssetSpecifier{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSpecifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSpecifier) ProtoMessage() {}

func (x *AssetSpecifier) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSpecifier.ProtoReflect.Descriptor instead.
func (*AssetSpecifier) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{1}
}

func (x *AssetSpecifier) GetId() isAssetSpecifier_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AssetSpecifier) GetAssetId() []byte {
	if x != nil {
		if x, ok := x.Id.(*AssetSpecifier_AssetId); ok {
			return x.AssetId
		}
	}
	return nil
}

func (x *AssetSpecifier) GetAssetIdStr() string {
	if x != nil {
		if x, ok := x.Id.(*AssetSpecifier_AssetIdStr); ok {
			return x.AssetIdStr
		}
	}
	return ""
}

func (x *AssetSpecifier) GetGroupKey() []byte {
	if x != nil {
		if x, ok := x.Id.(*AssetSpecifier_GroupKey); ok {
			return x.GroupKey
		}
	}
	return nil
}

func (x *AssetSpecifier) GetGroupKeyStr() string {
	if x != nil {
		if x, ok := x.Id.(*AssetSpecifier_GroupKeyStr); ok {
			return x.GroupKeyStr
		}
	}
	return ""
}

type isAssetSpecifier_Id interface {
	isAssetSpecifier_Id()
}

type AssetSpecifier_AssetId struct {
	// The 32-byte asset ID specified as raw bytes (gRPC only).
	AssetId []byte `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3,oneof"`
}

type AssetSpecifier_AssetIdStr struct {
	// The 32-byte asset ID encoded as a hex string (use this for REST).
	AssetIdStr string `protobuf:"bytes,2,opt,name=asset_id_str,json=assetIdStr,proto3,oneof"`
}

type AssetSpecifier_GroupKey struct {
	// The 32-byte asset group key specified as raw bytes (gRPC only).
	GroupKey []byte `protobuf:"bytes,3,opt,name=group_key,json=groupKey,proto3,oneof"`
}

type AssetSpecifier_GroupKeyStr struct {
	// The 32-byte asset group key encoded as hex string (use this for
	// REST).
	GroupKeyStr string `protobuf:"bytes,4,opt,name=group_key_str,json=groupKeyStr,proto3,oneof"`
}

func (*AssetSpecifier_AssetId) isAssetSpecifier_Id() {}

func (*AssetSpecifier_AssetIdStr) isAssetSpecifier_Id() {}

func (*AssetSpecifier_GroupKey) isAssetSpecifier_Id() {}

func (*AssetSpecifier_GroupKeyStr) isAssetSpecifier_Id() {}

// FixedPoint is a scaled integer representation of a fractional number.
//
// This type consists of two integer fields: a coefficient and a scale.
// Using this format enables precise and consistent representation of fractional
// numbers while avoiding floating-point data types, which are prone to
// precision errors.
//
// The relationship between the fractional representation and its fixed-point
// representation is expressed as:
// ```
// V = F_c / (10^F_s)
// ```
// where:
//
// * `V` is the fractional value.
//
//   - `F_c` is the coefficient component of the fixed-point representation. It is
//     the scaled-up fractional value represented as an integer.
//
//   - `F_s` is the scale component. It is an integer specifying how
//     many decimal places `F_c` should be divided by to obtain the fractional
//     representation.
type FixedPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The coefficient is the fractional value scaled-up as an integer. This
	// integer is represented as a string as it may be too large to fit in a
	// uint64.
	Coefficient string `protobuf:"bytes,1,opt,name=coefficient,proto3" json:"coefficient,omitempty"`
	// The scale is the component that determines how many decimal places
	// the coefficient should be divided by to obtain the fractional value.
	Scale         uint32 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedPoint) Reset() {
	*x = FixedPoint{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedPoint) ProtoMessage() {}

func (x *FixedPoint) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedPoint.ProtoReflect.Descriptor instead.
func (*FixedPoint) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{2}
}

func (x *FixedPoint) GetCoefficient() string {
	if x != nil {
		return x.Coefficient
	}
	return ""
}

func (x *FixedPoint) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// AssetRate represents the exchange rate of an asset to BTC along with an
// expiry timestamp in seconds.
type AssetRate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rate is the asset to BTC conversion rate represented as a fixed-point
	// number.
	Rate *FixedPoint `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	// expiry_timestamp is the Unix timestamp in seconds after which the rate
	// is no longer valid.
	ExpiryTimestamp uint64 `protobuf:"varint,2,opt,name=expiry_timestamp,json=expiryTimestamp,proto3" json:"expiry_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssetRate) Reset() {
	*x = AssetRate{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRate) ProtoMessage() {}

func (x *AssetRate) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetRate.ProtoReflect.Descriptor instead.
func (*AssetRate) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{3}
}

func (x *AssetRate) GetRate() *FixedPoint {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *AssetRate) GetExpiryTimestamp() uint64 {
	if x != nil {
		return x.ExpiryTimestamp
	}
	return 0
}

// BuyRequest represents a request to buy the subject asset.
type BuyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset_specifier is the subject asset.
	AssetSpecifier *AssetSpecifier `protobuf:"bytes,1,opt,name=asset_specifier,json=assetSpecifier,proto3" json:"asset_specifier,omitempty"`
	// asset_max_amount is the maximum amount of the asset that the peer must
	// be willing to offer.
	AssetMaxAmount uint64 `protobuf:"varint,2,opt,name=asset_max_amount,json=assetMaxAmount,proto3" json:"asset_max_amount,omitempty"`
	// asset_rate_hint is an optional suggested asset rate for the request.
	AssetRateHint *AssetRate `protobuf:"bytes,3,opt,name=asset_rate_hint,json=assetRateHint,proto3" json:"asset_rate_hint,omitempty"`
	// price_oracle_metadata is optional metadata for pricing decisions.
	PriceOracleMetadata string `protobuf:"bytes,4,opt,name=price_oracle_metadata,json=priceOracleMetadata,proto3" json:"price_oracle_metadata,omitempty"`
	// peer_id is the 33-byte public key of the counterparty peer.
	PeerId []byte `protobuf:"bytes,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// asset_min_amount is an optional minimum asset amount. A value of 0
	// means unset.
	AssetMinAmount uint64 `protobuf:"varint,6,opt,name=asset_min_amount,json=assetMinAmount,proto3" json:"asset_min_amount,omitempty"`
	// asset_rate_limit is an optional minimum acceptable rate (asset units
	// per BTC).
	AssetRateLimit *FixedPoint `protobuf:"bytes,7,opt,name=asset_rate_limit,json=assetRateLimit,proto3" json:"asset_rate_limit,omitempty"`
	// execution_policy is the optional execution policy for this request.
	ExecutionPolicy ExecutionPolicy `protobuf:"varint,8,opt,name=execution_policy,json=executionPolicy,proto3,enum=portfoliopilotrpc.ExecutionPolicy" json:"execution_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{4}
}

func (x *BuyRequest) GetAssetSpecifier() *AssetSpecifier {
	if x != nil {
		return x.AssetSpecifier
	}
	return nil
}

func (x *BuyRequest) GetAssetMaxAmount() uint64 {
	if x != nil {
		return x.AssetMaxAmount
	}
	return 0
}

func (x *BuyRequest) GetAssetRateHint() *AssetRate {
	if x != nil {
		return x.AssetRateHint
	}
	return nil
}

func (x *BuyRequest) GetPriceOracleMetadata() string {
	if x != nil {
		return x.PriceOracleMetadata
	}
	return ""
}

func (x *BuyRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *BuyRequest) GetAssetMinAmount() uint64 {
	if x != nil {
		return x.AssetMinAmount
	}
	return 0
}

func (x *BuyRequest) GetAssetRateLimit() *FixedPoint {
	if x != nil {
		return x.AssetRateLimit
	}
	return nil
}

func (x *BuyRequest) GetExecutionPolicy() ExecutionPolicy {
	if x != nil {
		return x.ExecutionPolicy
	}
	return ExecutionPolicy_EXECUTION_POLICY_IOC
}

// SellRequest represents a request to sell the subject asset.
type SellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset_specifier is the subject asset.
	AssetSpecifier *AssetSpecifier `protobuf:"bytes,1,opt,name=asset_specifier,json=assetSpecifier,proto3" json:"asset_specifier,omitempty"`
	// payment_max_amount is the maximum msat amount that the peer must agree
	// to pay.
	PaymentMaxAmount uint64 `protobuf:"varint,2,opt,name=payment_max_amount,json=paymentMaxAmount,proto3" json:"payment_max_amount,omitempty"`
	// asset_rate_hint is an optional suggested asset rate for the request.
	AssetRateHint *AssetRate `protobuf:"bytes,3,opt,name=asset_rate_hint,json=assetRateHint,proto3" json:"asset_rate_hint,omitempty"`
	// price_oracle_metadata is optional metadata for pricing decisions.
	PriceOracleMetadata string `protobuf:"bytes,4,opt,name=price_oracle_metadata,json=priceOracleMetadata,proto3" json:"price_oracle_metadata,omitempty"`
	// peer_id is the 33-byte public key of the counterparty peer.
	PeerId []byte `protobuf:"bytes,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// payment_min_amount is an optional minimum msat amount. A value of 0
	// means unset.
	PaymentMinAmount uint64 `protobuf:"varint,6,opt,name=payment_min_amount,json=paymentMinAmount,proto3" json:"payment_min_amount,omitempty"`
	// asset_rate_limit is an optional maximum acceptable rate (asset units
	// per BTC).
	AssetRateLimit *FixedPoint `protobuf:"bytes,7,opt,name=asset_rate_limit,json=assetRateLimit,proto3" json:"asset_rate_limit,omitempty"`
	// execution_policy is the optional execution policy for this request.
	ExecutionPolicy ExecutionPolicy `protobuf:"varint,8,opt,name=execution_policy,json=executionPolicy,proto3,enum=portfoliopilotrpc.ExecutionPolicy" json:"execution_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{5}
}

func (x *SellRequest) GetAssetSpecifier() *AssetSpecifier {
	if x != nil {
		return x.AssetSpecifier
	}
	return nil
}

func (x *SellRequest) GetPaymentMaxAmount() uint64 {
	if x != nil {
		return x.PaymentMaxAmount
	}
	return 0
}

func (x *SellRequest) GetAssetRateHint() *AssetRate {
	if x != nil {
		return x.AssetRateHint
	}
	return nil
}

func (x *SellRequest) GetPriceOracleMetadata() string {
	if x != nil {
		return x.PriceOracleMetadata
	}
	return ""
}

func (x *SellRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *SellRequest) GetPaymentMinAmount() uint64 {
	if x != nil {
		return x.PaymentMinAmount
	}
	return 0
}

func (x *SellRequest) GetAssetRateLimit() *FixedPoint {
	if x != nil {
		return x.AssetRateLimit
	}
	return nil
}

func (x *SellRequest) GetExecutionPolicy() ExecutionPolicy {
	if x != nil {
		return x.ExecutionPolicy
	}
	return ExecutionPolicy_EXECUTION_POLICY_IOC
}

// ResolveRequestRequest specifies a quote request to resolve.
type ResolveRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ResolveRequestRequest_BuyRequest
	//	*ResolveRequestRequest_SellRequest
	Request       isResolveRequestRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequestRequest) Reset() {
	*x = ResolveRequestRequest{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequestRequest) ProtoMessage() {}

func (x *ResolveRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequestRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequestRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveRequestRequest) GetRequest() isResolveRequestRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ResolveRequestRequest) GetBuyRequest() *BuyRequest {
	if x != nil {
		if x, ok := x.Request.(*ResolveRequestRequest_BuyRequest); ok {
			return x.BuyRequest
		}
	}
	return nil
}

func (x *ResolveRequestRequest) GetSellRequest() *SellRequest {
	if x != nil {
		if x, ok := x.Request.(*ResolveRequestRequest_SellRequest); ok {
			return x.SellRequest
		}
	}
	return nil
}

type isResolveRequestRequest_Request interface {
	isResolveRequestRequest_Request()
}

type ResolveRequestRequest_BuyRequest struct {
	// buy_request is a request to buy the subject asset.
	BuyRequest *BuyRequest `protobuf:"bytes,1,opt,name=buy_request,json=buyRequest,proto3,oneof"`
}

type ResolveRequestRequest_SellRequest struct {
	// sell_request is a request to sell the subject asset.
	SellRequest *SellRequest `protobuf:"bytes,2,opt,name=sell_request,json=sellRequest,proto3,oneof"`
}

func (*ResolveRequestRequest_BuyRequest) isResolveRequestRequest_Request() {}

func (*ResolveRequestRequest_SellRequest) isResolveRequestRequest_Request() {}

// ResolveRequestResponse is the response to a ResolveRequest call.
type ResolveRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ResolveRequestResponse_Accept
	//	*ResolveRequestResponse_Reject
	Result isResolveRequestResponse_Result `protobuf_oneof:"result"`
	// accepted_max_amount is an optional fill quantity that caps the
	// amount the responder is willing to accept. Only meaningful when
	// accept is set; 0 means no fill cap (full request max). The unit
	// depends on the request type: asset units for a buy request, msat
	// for a sell request.
	AcceptedMaxAmount uint64 `protobuf:"varint,3,opt,name=accepted_max_amount,json=acceptedMaxAmount,proto3" json:"accepted_max_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveRequestResponse) Reset() {
	*x = ResolveRequestResponse{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequestResponse) ProtoMessage() {}

func (x *ResolveRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequestResponse.ProtoReflect.Descriptor instead.
func (*ResolveRequestResponse) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveRequestResponse) GetResult() isResolveRequestResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResolveRequestResponse) GetAccept() *AssetRate {
	if x != nil {
		if x, ok := x.Result.(*ResolveRequestResponse_Accept); ok {
			return x.Accept
		}
	}
	return nil
}

func (x *ResolveRequestResponse) GetReject() *RejectErr {
	if x != nil {
		if x, ok := x.Result.(*ResolveRequestResponse_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

func (x *ResolveRequestResponse) GetAcceptedMaxAmount() uint64 {
	if x != nil {
		return x.AcceptedMaxAmount
	}
	return 0
}

type isResolveRequestResponse_Result interface {
	isResolveRequestResponse_Result()
}

type ResolveRequestResponse_Accept struct {
	// accept is the accepted asset rate for the request.
	Accept *AssetRate `protobuf:"bytes,1,opt,name=accept,proto3,oneof"`
}

type ResolveRequestResponse_Reject struct {
	// reject is the rejection reason for the request.
	Reject *RejectErr `protobuf:"bytes,2,opt,name=reject,proto3,oneof"`
}

func (*ResolveRequestResponse_Accept) isResolveRequestResponse_Result() {}

func (*ResolveRequestResponse_Reject) isResolveRequestResponse_Result() {}

// AcceptedQuote bundles an accepted quote and its original request.
type AcceptedQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_id is the 33-byte public key of the accepting peer.
	PeerId []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// accepted_rate is the asset rate accepted by the peer.
	AcceptedRate *AssetRate `protobuf:"bytes,2,opt,name=accepted_rate,json=acceptedRate,proto3" json:"accepted_rate,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*AcceptedQuote_BuyRequest
	//	*AcceptedQuote_SellRequest
	Request isAcceptedQuote_Request `protobuf_oneof:"request"`
	// accepted_max_amount is the optional negotiated fill quantity.
	// 0 means no fill cap (full request max). The unit depends on
	// the request type: asset units for a buy request, msat for a
	// sell request.
	AcceptedMaxAmount uint64 `protobuf:"varint,5,opt,name=accepted_max_amount,json=acceptedMaxAmount,proto3" json:"accepted_max_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AcceptedQuote) Reset() {
	*x = AcceptedQuote{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedQuote) ProtoMessage() {}

func (x *AcceptedQuote) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedQuote.ProtoReflect.Descriptor instead.
func (*AcceptedQuote) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptedQuote) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *AcceptedQuote) GetAcceptedRate() *AssetRate {
	if x != nil {
		return x.AcceptedRate
	}
	return nil
}

func (x *AcceptedQuote) GetRequest() isAcceptedQuote_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AcceptedQuote) GetBuyRequest() *BuyRequest {
	if x != nil {
		if x, ok := x.Request.(*AcceptedQuote_BuyRequest); ok {
			return x.BuyRequest
		}
	}
	return nil
}

func (x *AcceptedQuote) GetSellRequest() *SellRequest {
	if x != nil {
		if x, ok := x.Request.(*AcceptedQuote_SellRequest); ok {
			return x.SellRequest
		}
	}
	return nil
}

func (x *AcceptedQuote) GetAcceptedMaxAmount() uint64 {
	if x != nil {
		return x.AcceptedMaxAmount
	}
	return 0
}

type isAcceptedQuote_Request interface {
	isAcceptedQuote_Request()
}

type AcceptedQuote_BuyRequest struct {
	// buy_request is the original buy request.
	BuyRequest *BuyRequest `protobuf:"bytes,3,opt,name=buy_request,json=buyRequest,proto3,oneof"`
}

type AcceptedQuote_SellRequest struct {
	// sell_request is the original sell request.
	SellRequest *SellRequest `protobuf:"bytes,4,opt,name=sell_request,json=sellRequest,proto3,oneof"`
}

func (*AcceptedQuote_BuyRequest) isAcceptedQuote_Request() {}

func (*AcceptedQuote_SellRequest) isAcceptedQuote_Request() {}

// VerifyAcceptQuoteRequest specifies an accepted quote to verify.
type VerifyAcceptQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accept is the accepted quote and request details.
	Accept        *AcceptedQuote `protobuf:"bytes,1,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAcceptQuoteRequest) Reset() {
	*x = VerifyAcceptQuoteRequest{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAcceptQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAcceptQuoteRequest) ProtoMessage() {}

func (x *VerifyAcceptQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAcceptQuoteRequest.ProtoReflect.Descriptor instead.
func (*VerifyAcceptQuoteRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyAcceptQuoteRequest) GetAccept() *AcceptedQuote {
	if x != nil {
		return x.Accept
	}
	return nil
}

// VerifyAcceptQuoteResponse is the response to a VerifyAcceptQuote call.
type VerifyAcceptQuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the verification result.
	Status        QuoteRespStatus `protobuf:"varint,1,opt,name=status,proto3,enum=portfoliopilotrpc.QuoteRespStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAcceptQuoteResponse) Reset() {
	*x = VerifyAcceptQuoteResponse{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAcceptQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAcceptQuoteResponse) ProtoMessage() {}

func (x *VerifyAcceptQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAcceptQuoteResponse.ProtoReflect.Descriptor instead.
func (*VerifyAcceptQuoteResponse) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyAcceptQuoteResponse) GetStatus() QuoteRespStatus {
	if x != nil {
		return x.Status
	}
	return QuoteRespStatus_INVALID_ASSET_RATES
}

// QueryAssetRatesRequest specifies the parameters for querying asset rates.
type QueryAssetRatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset_specifier identifies the subject asset.
	AssetSpecifier *AssetSpecifier `protobuf:"bytes,1,opt,name=asset_specifier,json=assetSpecifier,proto3" json:"asset_specifier,omitempty"`
	// direction specifies whether we want to buy or sell the asset.
	Direction AssetTransferDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=portfoliopilotrpc.AssetTransferDirection" json:"direction,omitempty"`
	// intent specifies the purpose of the query.
	Intent Intent `protobuf:"varint,3,opt,name=intent,proto3,enum=portfoliopilotrpc.Intent" json:"intent,omitempty"`
	// asset_amount is an optional constraint on the asset amount. If set to
	// zero, it is considered unset.
	AssetAmount uint64 `protobuf:"varint,4,opt,name=asset_amount,json=assetAmount,proto3" json:"asset_amount,omitempty"`
	// payment_amount is an optional constraint on the payment amount in msat.
	// If set to zero, it is considered unset.
	PaymentAmount uint64 `protobuf:"varint,5,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	// asset_rate_hint is an optional suggested asset rate.
	AssetRateHint *AssetRate `protobuf:"bytes,6,opt,name=asset_rate_hint,json=assetRateHint,proto3" json:"asset_rate_hint,omitempty"`
	// price_oracle_metadata is optional metadata for pricing decisions.
	PriceOracleMetadata string `protobuf:"bytes,7,opt,name=price_oracle_metadata,json=priceOracleMetadata,proto3" json:"price_oracle_metadata,omitempty"`
	// peer_id is the 33-byte public key of the counterparty peer.
	PeerId []byte `protobuf:"bytes,8,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// expiry_timestamp is an optional expiry Unix timestamp (seconds) for the
	// query context. If set to zero, it is considered unset.
	ExpiryTimestamp uint64 `protobuf:"varint,9,opt,name=expiry_timestamp,json=expiryTimestamp,proto3" json:"expiry_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryAssetRatesRequest) Reset() {
	*x = QueryAssetRatesRequest{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAssetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAssetRatesRequest) ProtoMessage() {}

func (x *QueryAssetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAssetRatesRequest.ProtoReflect.Descriptor instead.
func (*QueryAssetRatesRequest) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{11}
}

func (x *QueryAssetRatesRequest) GetAssetSpecifier() *AssetSpecifier {
	if x != nil {
		return x.AssetSpecifier
	}
	return nil
}

func (x *QueryAssetRatesRequest) GetDirection() AssetTransferDirection {
	if x != nil {
		return x.Direction
	}
	return AssetTransferDirection_ASSET_TRANSFER_DIRECTION_UNSPECIFIED
}

func (x *QueryAssetRatesRequest) GetIntent() Intent {
	if x != nil {
		return x.Intent
	}
	return Intent_INTENT_UNSPECIFIED
}

func (x *QueryAssetRatesRequest) GetAssetAmount() uint64 {
	if x != nil {
		return x.AssetAmount
	}
	return 0
}

func (x *QueryAssetRatesRequest) GetPaymentAmount() uint64 {
	if x != nil {
		return x.PaymentAmount
	}
	return 0
}

func (x *QueryAssetRatesRequest) GetAssetRateHint() *AssetRate {
	if x != nil {
		return x.AssetRateHint
	}
	return nil
}

func (x *QueryAssetRatesRequest) GetPriceOracleMetadata() string {
	if x != nil {
		return x.PriceOracleMetadata
	}
	return ""
}

func (x *QueryAssetRatesRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *QueryAssetRatesRequest) GetExpiryTimestamp() uint64 {
	if x != nil {
		return x.ExpiryTimestamp
	}
	return 0
}

// QueryAssetRatesResponse is the response to a QueryAssetRates call.
type QueryAssetRatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset_rate is the asset exchange rate response.
	AssetRate     *AssetRate `protobuf:"bytes,1,opt,name=asset_rate,json=assetRate,proto3" json:"asset_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAssetRatesResponse) Reset() {
	*x = QueryAssetRatesResponse{}
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAssetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAssetRatesResponse) ProtoMessage() {}

func (x *QueryAssetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAssetRatesResponse.ProtoReflect.Descriptor instead.
func (*QueryAssetRatesResponse) Descriptor() ([]byte, []int) {
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP(), []int{12}
}

func (x *QueryAssetRatesResponse) GetAssetRate() *AssetRate {
	if x != nil {
		return x.AssetRate
	}
	return nil
}

var File_portfoliopilotrpc_portfolio_pilot_proto protoreflect.FileDescriptor

const file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc = "" +
	"\n" +
	"'portfoliopilotrpc/portfolio_pilot.proto\x12\x11portfoliopilotrpc\"X\n" +
	"\tRejectErr\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.portfoliopilotrpc.RejectCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x01\n" +
	"\x0eAssetSpecifier\x12\x1b\n" +
	"\basset_id\x18\x01 \x01(\fH\x00R\aassetId\x12\"\n" +
	"\fasset_id_str\x18\x02 \x01(\tH\x00R\n" +
	"assetIdStr\x12\x1d\n" +
	"\tgroup_key\x18\x03 \x01(\fH\x00R\bgroupKey\x12$\n" +
	"\rgroup_key_str\x18\x04 \x01(\tH\x00R\vgroupKeyStrB\x04\n" +
	"\x02id\"D\n" +
	"\n" +
	"FixedPoint\x12 \n" +
	"\vcoefficient\x18\x01 \x01(\tR\vcoefficient\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\rR\x05scale\"i\n" +
	"\tAssetRate\x121\n" +
	"\x04rate\x18\x01 \x01(\v2\x1d.portfoliopilotrpc.FixedPointR\x04rate\x12)\n" +
	"\x10expiry_timestamp\x18\x02 \x01(\x04R\x0fexpiryTimestamp\"\xd7\x03\n" +
	"\n" +
	"BuyRequest\x12J\n" +
	"\x0fasset_specifier\x18\x01 \x01(\v2!.portfoliopilotrpc.AssetSpecifierR\x0eassetSpecifier\x12(\n" +
	"\x10asset_max_amount\x18\x02 \x01(\x04R\x0eassetMaxAmount\x12D\n" +
	"\x0fasset_rate_hint\x18\x03 \x01(\v2\x1c.portfoliopilotrpc.AssetRateR\rassetRateHint\x122\n" +
	"\x15price_oracle_metadata\x18\x04 \x01(\tR\x13priceOracleMetadata\x12\x17\n" +
	"\apeer_id\x18\x05 \x01(\fR\x06peerId\x12(\n" +
	"\x10asset_min_amount\x18\x06 \x01(\x04R\x0eassetMinAmount\x12G\n" +
	"\x10asset_rate_limit\x18\a \x01(\v2\x1d.portfoliopilotrpc.FixedPointR\x0eassetRateLimit\x12M\n" +
	"\x10execution_policy\x18\b \x01(\x0e2\".portfoliopilotrpc.ExecutionPolicyR\x0fexecutionPolicy\"\xe0\x03\n" +
	"\vSellRequest\x12J\n" +
	"\x0fasset_specifier\x18\x01 \x01(\v2!.portfoliopilotrpc.AssetSpecifierR\x0eassetSpecifier\x12,\n" +
	"\x12payment_max_amount\x18\x02 \x01(\x04R\x10paymentMaxAmount\x12D\n" +
	"\x0fasset_rate_hint\x18\x03 \x01(\v2\x1c.portfoliopilotrpc.AssetRateR\rassetRateHint\x122\n" +
	"\x15price_oracle_metadata\x18\x04 \x01(\tR\x13priceOracleMetadata\x12\x17\n" +
	"\apeer_id\x18\x05 \x01(\fR\x06peerId\x12,\n" +
	"\x12payment_min_amount\x18\x06 \x01(\x04R\x10paymentMinAmount\x12G\n" +
	"\x10asset_rate_limit\x18\a \x01(\v2\x1d.portfoliopilotrpc.FixedPointR\x0eassetRateLimit\x12M\n" +
	"\x10execution_policy\x18\b \x01(\x0e2\".portfoliopilotrpc.ExecutionPolicyR\x0fexecutionPolicy\"\xa9\x01\n" +
	"\x15ResolveRequestRequest\x12@\n" +
	"\vbuy_request\x18\x01 \x01(\v2\x1d.portfoliopilotrpc.BuyRequestH\x00R\n" +
	"buyRequest\x12C\n" +
	"\fsell_request\x18\x02 \x01(\v2\x1e.portfoliopilotrpc.SellRequestH\x00R\vsellRequestB\t\n" +
	"\arequest\"\xc2\x01\n" +
	"\x16ResolveRequestResponse\x126\n" +
	"\x06accept\x18\x01 \x01(\v2\x1c.portfoliopilotrpc.AssetRateH\x00R\x06accept\x126\n" +
	"\x06reject\x18\x02 \x01(\v2\x1c.portfoliopilotrpc.RejectErrH\x00R\x06reject\x12.\n" +
	"\x13accepted_max_amount\x18\x03 \x01(\x04R\x11acceptedMaxAmountB\b\n" +
	"\x06result\"\xad\x02\n" +
	"\rAcceptedQuote\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12A\n" +
	"\raccepted_rate\x18\x02 \x01(\v2\x1c.portfoliopilotrpc.AssetRateR\facceptedRate\x12@\n" +
	"\vbuy_request\x18\x03 \x01(\v2\x1d.portfoliopilotrpc.BuyRequestH\x00R\n" +
	"buyRequest\x12C\n" +
	"\fsell_request\x18\x04 \x01(\v2\x1e.portfoliopilotrpc.SellRequestH\x00R\vsellRequest\x12.\n" +
	"\x13accepted_max_amount\x18\x05 \x01(\x04R\x11acceptedMaxAmountB\t\n" +
	"\arequest\"T\n" +
	"\x18VerifyAcceptQuoteRequest\x128\n" +
	"\x06accept\x18\x01 \x01(\v2 .portfoliopilotrpc.AcceptedQuoteR\x06accept\"W\n" +
	"\x19VerifyAcceptQuoteResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".portfoliopilotrpc.QuoteRespStatusR\x06status\"\xe8\x03\n" +
	"\x16QueryAssetRatesRequest\x12J\n" +
	"\x0fasset_specifier\x18\x01 \x01(\v2!.portfoliopilotrpc.AssetSpecifierR\x0eassetSpecifier\x12G\n" +
	"\tdirection\x18\x02 \x01(\x0e2).portfoliopilotrpc.AssetTransferDirectionR\tdirection\x121\n" +
	"\x06intent\x18\x03 \x01(\x0e2\x19.portfoliopilotrpc.IntentR\x06intent\x12!\n" +
	"\fasset_amount\x18\x04 \x01(\x04R\vassetAmount\x12%\n" +
	"\x0epayment_amount\x18\x05 \x01(\x04R\rpaymentAmount\x12D\n" +
	"\x0fasset_rate_hint\x18\x06 \x01(\v2\x1c.portfoliopilotrpc.AssetRateR\rassetRateHint\x122\n" +
	"\x15price_oracle_metadata\x18\a \x01(\tR\x13priceOracleMetadata\x12\x17\n" +
	"\apeer_id\x18\b \x01(\fR\x06peerId\x12)\n" +
	"\x10expiry_timestamp\x18\t \x01(\x04R\x0fexpiryTimestamp\"V\n" +
	"\x17QueryAssetRatesResponse\x12;\n" +
	"\n" +
	"asset_rate\x18\x01 \x01(\v2\x1c.portfoliopilotrpc.AssetRateR\tassetRate*\x87\x01\n" +
	"\x16AssetTransferDirection\x12(\n" +
	"$ASSET_TRANSFER_DIRECTION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cASSET_TRANSFER_DIRECTION_BUY\x10\x01\x12!\n" +
	"\x1dASSET_TRANSFER_DIRECTION_SELL\x10\x02*\xcd\x01\n" +
	"\x06Intent\x12\x16\n" +
	"\x12INTENT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17INTENT_PAY_INVOICE_HINT\x10\x01\x12\x16\n" +
	"\x12INTENT_PAY_INVOICE\x10\x02\x12\x1e\n" +
	"\x1aINTENT_PAY_INVOICE_QUALIFY\x10\x03\x12\x1c\n" +
	"\x18INTENT_RECV_PAYMENT_HINT\x10\x04\x12\x17\n" +
	"\x13INTENT_RECV_PAYMENT\x10\x05\x12\x1f\n" +
	"\x1bINTENT_RECV_PAYMENT_QUALIFY\x10\x06*E\n" +
	"\x0fExecutionPolicy\x12\x18\n" +
	"\x14EXECUTION_POLICY_IOC\x10\x00\x12\x18\n" +
	"\x14EXECUTION_POLICY_FOK\x10\x01*\xd9\x01\n" +
	"\n" +
	"RejectCode\x12\x1b\n" +
	"\x17REJECT_CODE_UNSPECIFIED\x10\x00\x12(\n" +
	"$REJECT_CODE_PRICE_ORACLE_UNAVAILABLE\x10\x01\x12 \n" +
	"\x1cREJECT_CODE_MIN_FILL_NOT_MET\x10\x02\x12 \n" +
	"\x1cREJECT_CODE_PRICE_BOUND_MISS\x10\x03\x12\x1e\n" +
	"\x1aREJECT_CODE_FOK_NOT_VIABLE\x10\x04\x12 \n" +
	"\x1cREJECT_CODE_FILL_EXCEEDS_MAX\x10\x05*\xe0\x01\n" +
	"\x0fQuoteRespStatus\x12\x17\n" +
	"\x13INVALID_ASSET_RATES\x10\x00\x12\x12\n" +
	"\x0eINVALID_EXPIRY\x10\x01\x12\x1a\n" +
	"\x16PRICE_ORACLE_QUERY_ERR\x10\x02\x12\x17\n" +
	"\x13PORTFOLIO_PILOT_ERR\x10\x03\x12\x16\n" +
	"\x12VALID_ACCEPT_QUOTE\x10\x04\x12\x14\n" +
	"\x10MIN_FILL_NOT_MET\x10\x05\x12\x13\n" +
	"\x0fRATE_BOUND_MISS\x10\x06\x12\x12\n" +
	"\x0eFOK_NOT_VIABLE\x10\a\x12\x14\n" +
	"\x10FILL_EXCEEDS_MAX\x10\b2\xd1\x02\n" +
	"\x0ePortfolioPilot\x12e\n" +
	"\x0eResolveRequest\x12(.portfoliopilotrpc.ResolveRequestRequest\x1a).portfoliopilotrpc.ResolveRequestResponse\x12n\n" +
	"\x11VerifyAcceptQuote\x12+.portfoliopilotrpc.VerifyAcceptQuoteRequest\x1a,.portfoliopilotrpc.VerifyAcceptQuoteResponse\x12h\n" +
	"\x0fQueryAssetRates\x12).portfoliopilotrpc.QueryAssetRatesRequest\x1a*.portfoliopilotrpc.QueryAssetRatesResponseBBZ@github.com/lightninglabs/taproot-assets/taprpc/portfoliopilotrpcb\x06proto3"

var (
	file_portfoliopilotrpc_portfolio_pilot_proto_rawDescOnce sync.Once
	file_portfoliopilotrpc_portfolio_pilot_proto_rawDescData []byte
)

func file_portfoliopilotrpc_portfolio_pilot_proto_rawDescGZIP() []byte {
	file_portfoliopilotrpc_portfolio_pilot_proto_rawDescOnce.Do(func() {
		file_portfoliopilotrpc_portfolio_pilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc), len(file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc)))
	})
	return file_portfoliopilotrpc_portfolio_pilot_proto_rawDescData
}

var file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_portfoliopilotrpc_portfolio_pilot_proto_goTypes = []any{
	(AssetTransferDirection)(0),       // 0: portfoliopilotrpc.AssetTransferDirection
	(Intent)(0),                       // 1: portfoliopilotrpc.Intent
	(ExecutionPolicy)(0),              // 2: portfoliopilotrpc.ExecutionPolicy
	(RejectCode)(0),                   // 3: portfoliopilotrpc.RejectCode
	(QuoteRespStatus)(0),              // 4: portfoliopilotrpc.QuoteRespStatus
	(*RejectErr)(nil),                 // 5: portfoliopilotrpc.RejectErr
	(*AssetSpecifier)(nil),            // 6: portfoliopilotrpc.AssetSpecifier
	(*FixedPoint)(nil),                // 7: portfoliopilotrpc.FixedPoint
	(*AssetRate)(nil),                 // 8: portfoliopilotrpc.AssetRate
	(*BuyRequest)(nil),                // 9: portfoliopilotrpc.BuyRequest
	(*SellRequest)(nil),               // 10: portfoliopilotrpc.SellRequest
	(*ResolveRequestRequest)(nil),     // 11: portfoliopilotrpc.ResolveRequestRequest
	(*ResolveRequestResponse)(nil),    // 12: portfoliopilotrpc.ResolveRequestResponse
	(*AcceptedQuote)(nil),             // 13: portfoliopilotrpc.AcceptedQuote
	(*VerifyAcceptQuoteRequest)(nil),  // 14: portfoliopilotrpc.VerifyAcceptQuoteRequest
	(*VerifyAcceptQuoteResponse)(nil), // 15: portfoliopilotrpc.VerifyAcceptQuoteResponse
	(*QueryAssetRatesRequest)(nil),    // 16: portfoliopilotrpc.QueryAssetRatesRequest
	(*QueryAssetRatesResponse)(nil),   // 17: portfoliopilotrpc.QueryAssetRatesResponse
}
var file_portfoliopilotrpc_portfolio_pilot_proto_depIdxs = []int32{
	3,  // 0: portfoliopilotrpc.RejectErr.code:type_name -> portfoliopilotrpc.RejectCode
	7,  // 1: portfoliopilotrpc.AssetRate.rate:type_name -> portfoliopilotrpc.FixedPoint
	6,  // 2: portfoliopilotrpc.BuyRequest.asset_specifier:type_name -> portfoliopilotrpc.AssetSpecifier
	8,  // 3: portfoliopilotrpc.BuyRequest.asset_rate_hint:type_name -> portfoliopilotrpc.AssetRate
	7,  // 4: portfoliopilotrpc.BuyRequest.asset_rate_limit:type_name -> portfoliopilotrpc.FixedPoint
	2,  // 5: portfoliopilotrpc.BuyRequest.execution_policy:type_name -> portfoliopilotrpc.ExecutionPolicy
	6,  // 6: portfoliopilotrpc.SellRequest.asset_specifier:type_name -> portfoliopilotrpc.AssetSpecifier
	8,  // 7: portfoliopilotrpc.SellRequest.asset_rate_hint:type_name -> portfoliopilotrpc.AssetRate
	7,  // 8: portfoliopilotrpc.SellRequest.asset_rate_limit:type_name -> portfoliopilotrpc.FixedPoint
	2,  // 9: portfoliopilotrpc.SellRequest.execution_policy:type_name -> portfoliopilotrpc.ExecutionPolicy
	9,  // 10: portfoliopilotrpc.ResolveRequestRequest.buy_request:type_name -> portfoliopilotrpc.BuyRequest
	10, // 11: portfoliopilotrpc.ResolveRequestRequest.sell_request:type_name -> portfoliopilotrpc.SellRequest
	8,  // 12: portfoliopilotrpc.ResolveRequestResponse.accept:type_name -> portfoliopilotrpc.AssetRate
	5,  // 13: portfoliopilotrpc.ResolveRequestResponse.reject:type_name -> portfoliopilotrpc.RejectErr
	8,  // 14: portfoliopilotrpc.AcceptedQuote.accepted_rate:type_name -> portfoliopilotrpc.AssetRate
	9,  // 15: portfoliopilotrpc.AcceptedQuote.buy_request:type_name -> portfoliopilotrpc.BuyRequest
	10, // 16: portfoliopilotrpc.AcceptedQuote.sell_request:type_name -> portfoliopilotrpc.SellRequest
	13, // 17: portfoliopilotrpc.VerifyAcceptQuoteRequest.accept:type_name -> portfoliopilotrpc.AcceptedQuote
	4,  // 18: portfoliopilotrpc.VerifyAcceptQuoteResponse.status:type_name -> portfoliopilotrpc.QuoteRespStatus
	6,  // 19: portfoliopilotrpc.QueryAssetRatesRequest.asset_specifier:type_name -> portfoliopilotrpc.AssetSpecifier
	0,  // 20: portfoliopilotrpc.QueryAssetRatesRequest.direction:type_name -> portfoliopilotrpc.AssetTransferDirection
	1,  // 21: portfoliopilotrpc.QueryAssetRatesRequest.intent:type_name -> portfoliopilotrpc.Intent
	8,  // 22: portfoliopilotrpc.QueryAssetRatesRequest.asset_rate_hint:type_name -> portfoliopilotrpc.AssetRate
	8,  // 23: portfoliopilotrpc.QueryAssetRatesResponse.asset_rate:type_name -> portfoliopilotrpc.AssetRate
	11, // 24: portfoliopilotrpc.PortfolioPilot.ResolveRequest:input_type -> portfoliopilotrpc.ResolveRequestRequest
	14, // 25: portfoliopilotrpc.PortfolioPilot.VerifyAcceptQuote:input_type -> portfoliopilotrpc.VerifyAcceptQuoteRequest
	16, // 26: portfoliopilotrpc.PortfolioPilot.QueryAssetRates:input_type -> portfoliopilotrpc.QueryAssetRatesRequest
	12, // 27: portfoliopilotrpc.PortfolioPilot.ResolveRequest:output_type -> portfoliopilotrpc.ResolveRequestResponse
	15, // 28: portfoliopilotrpc.PortfolioPilot.VerifyAcceptQuote:output_type -> portfoliopilotrpc.VerifyAcceptQuoteResponse
	17, // 29: portfoliopilotrpc.PortfolioPilot.QueryAssetRates:output_type -> portfoliopilotrpc.QueryAssetRatesResponse
	27, // [27:30] is the sub-list for method output_type
	24, // [24:27] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_portfoliopilotrpc_portfolio_pilot_proto_init() }
func file_portfoliopilotrpc_portfolio_pilot_proto_init() {
	if File_portfoliopilotrpc_portfolio_pilot_proto != nil {
		return
	}
	file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[1].OneofWrappers = []any{
		(*AssetSpecifier_AssetId)(nil),
		(*AssetSpecifier_AssetIdStr)(nil),
		(*AssetSpecifier_GroupKey)(nil),
		(*AssetSpecifier_GroupKeyStr)(nil),
	}
	file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[6].OneofWrappers = []any{
		(*ResolveRequestRequest_BuyRequest)(nil),
		(*ResolveRequestRequest_SellRequest)(nil),
	}
	file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[7].OneofWrappers = []any{
		(*ResolveRequestResponse_Accept)(nil),
		(*ResolveRequestResponse_Reject)(nil),
	}
	file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes[8].OneofWrappers = []any{
		(*AcceptedQuote_BuyRequest)(nil),
		(*AcceptedQuote_SellRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc), len(file_portfoliopilotrpc_portfolio_pilot_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfoliopilotrpc_portfolio_pilot_proto_goTypes,
		DependencyIndexes: file_portfoliopilotrpc_portfolio_pilot_proto_depIdxs,
		EnumInfos:         file_portfoliopilotrpc_portfolio_pilot_proto_enumTypes,
		MessageInfos:      file_portfoliopilotrpc_portfolio_pilot_proto_msgTypes,
	}.Build()
	File_portfoliopilotrpc_portfolio_pilot_proto = out.File
	file_portfoliopilotrpc_portfolio_pilot_proto_goTypes = nil
	file_portfoliopilotrpc_portfolio_pilot_proto_depIdxs = nil
}
